### ISSUE TITLE
Can I rebuild  vlc-qt library files with CMake?

### ISSUE THREAD

**Issue by TheBinary001** [vlc-qt/vlc-qt#101]
Hi,

I'm a newbie with CMake on cross platform. I tried to  add a new function in vlc-qt source and reconfigure and regenerate with CMake 3.3.0 Gui.
CMake shows as follow:

The C compiler identification is GNU 4.8.1
The CXX compiler identification is GNU 4.8.1
Check for working C compiler: C:/MinGW/bin/gcc.exe
Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/MinGW/bin/g++.exe
Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
VLC-Qt: Build with Qt5
VLC-Qt: Build with Widgets: ON
VLC-Qt: Build with QML: ON
VLC-Qt: Build with Angle: OFF
VLC-Qt: Build with OpenGL ES2: OFF
VLC-Qt: Build statically: OFF
Found LibVLC include-dir path: C:/Program Files/VideoLAN/VLC/sdk/include
Found LibVLC library path:C:/Program Files/VideoLAN/VLC/libvlc.dll
Found LibVLCcore library path:C:/Program Files/VideoLAN/VLC/libvlccore.dll

VLC-Qt: You are compiling libvlc-qt 0.10.0

VLC-Qt: Build tests: OFF

Configuring done
Generating done

But there is no new library files such as : libvlc-qt.dll.a, libvlc-qt-qml.dll.a. libvlc-qt-widgets.dll.a.
How can I build these library files that added my new function? Can I rebuild these library files with CMake?
My system is Windows7 32bit, Qt C++5.4, MinGW, CMake 3.3.0.

Thanks.

**Comment by ntadej** [comment]
You need to run your desired make, so in this case mingw32-make. CMake just configures the project.

**Comment by TheBinary001** [comment]
Thank ntadej for your replay.

But I run mingw32-make 
It gives errors. How can I fix it?

D:\buildOutput>mingw32-make
E:\cmake33\bin\cmake.exe -HD:\vlc-qt-master -BD:\buildOutput --check-build-syste
m CMakeFiles\Makefile.cmake 0
E:\cmake33\bin\cmake.exe -E cmake_progress_start D:\buildOutput\CMakeFiles D:\bu
ildOutput\CMakeFiles\progress.marks
mingw32-make -f CMakeFiles\Makefile2 all
mingw32-make[1]: Entering directory 'D:/buildOutput'
mingw32-make -f src\core\CMakeFiles\vlc-qt-core_automoc.dir\build.make src/core/
CMakeFiles/vlc-qt-core_automoc.dir/depend
mingw32-make[2]: Entering directory 'D:/buildOutput'
E:\cmake33\bin\cmake.exe -E cmake_depends "MinGW Makefiles" D:\vlc-qt-master D:\
vlc-qt-master\src\core D:\buildOutput D:\buildOutput\src\core D:\buildOutput\src
\core\CMakeFiles\vlc-qt-core_automoc.dir\DependInfo.cmake --color=
Scanning dependencies of target vlc-qt-core_automoc
mingw32-make[2]: Leaving directory 'D:/buildOutput'
mingw32-make -f src\core\CMakeFiles\vlc-qt-core_automoc.dir\build.make src/core/
CMakeFiles/vlc-qt-core_automoc.dir/build
mingw32-make[2]: Entering directory 'D:/buildOutput'
[  2%] Automatic moc, uic and rcc for target vlc-qt-core
cd /d D:\buildOutput\src\core && E:\cmake33\bin\cmake.exe -E cmake_autogen D:/bu
ildOutput/src/core/CMakeFiles/vlc-qt-core_automoc.dir/ ""
Generating moc_Audio.cpp
Generating moc_Enums.cpp
Generating moc_Equalizer.cpp
Generating moc_Instance.cpp
Generating moc_Media.cpp
Generating moc_MediaList.cpp
Generating moc_MediaListPlayer.cpp
Generating moc_MediaPlayer.cpp
Generating moc_Video.cpp
mingw32-make[2]: Leaving directory 'D:/buildOutput'
[  2%] Built target vlc-qt-core_automoc
mingw32-make -f src\core\CMakeFiles\vlc-qt-core.dir\build.make src/core/CMakeFil
es/vlc-qt-core.dir/depend
mingw32-make[2]: Entering directory 'D:/buildOutput'
[  5%] Generating ../../platform/windows/core.obj
cd /d D:\vlc-qt-master\platform\windows && C:\MinGW\bin\windres.exe -i D:/buildO
utput/platform/windows/core.rc -o D:/buildOutput/platform/windows/core.obj
E:\cmake33\bin\cmake.exe -E cmake_depends "MinGW Makefiles" D:\vlc-qt-master D:\
vlc-qt-master\src\core D:\buildOutput D:\buildOutput\src\core D:\buildOutput\src
\core\CMakeFiles\vlc-qt-core.dir\DependInfo.cmake --color=
Scanning dependencies of target vlc-qt-core
mingw32-make[2]: Leaving directory 'D:/buildOutput'
mingw32-make -f src\core\CMakeFiles\vlc-qt-core.dir\build.make src/core/CMakeFil
es/vlc-qt-core.dir/build
mingw32-make[2]: Entering directory 'D:/buildOutput'
[  8%] Building CXX object src/core/CMakeFiles/vlc-qt-core.dir/Audio.cpp.obj
cd /d D:\buildOutput\src\core && C:\MinGW\bin\g++.exe   -DQT_CORE_LIB -DQT_NO_DE
BUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REENTRANT -Dvlc_qt_core_EXPORTS -std=c++
11 @CMakeFiles/vlc-qt-core.dir/includes_CXX.rsp   -o CMakeFiles\vlc-qt-core.dir\
Audio.cpp.obj -c D:\vlc-qt-master\src\core\Audio.cpp
[ 11%] Building CXX object src/core/CMakeFiles/vlc-qt-core.dir/Common.cpp.obj
cd /d D:\buildOutput\src\core && C:\MinGW\bin\g++.exe   -DQT_CORE_LIB -DQT_NO_DE
BUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REENTRANT -Dvlc_qt_core_EXPORTS -std=c++
11 @CMakeFiles/vlc-qt-core.dir/includes_CXX.rsp   -o CMakeFiles\vlc-qt-core.dir\
Common.cpp.obj -c D:\vlc-qt-master\src\core\Common.cpp
[ 14%] Building CXX object src/core/CMakeFiles/vlc-qt-core.dir/Enums.cpp.obj
cd /d D:\buildOutput\src\core && C:\MinGW\bin\g++.exe   -DQT_CORE_LIB -DQT_NO_DE
BUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REENTRANT -Dvlc_qt_core_EXPORTS -std=c++
11 @CMakeFiles/vlc-qt-core.dir/includes_CXX.rsp   -o CMakeFiles\vlc-qt-core.dir\
Enums.cpp.obj -c D:\vlc-qt-master\src\core\Enums.cpp
[ 17%] Building CXX object src/core/CMakeFiles/vlc-qt-core.dir/Error.cpp.obj
cd /d D:\buildOutput\src\core && C:\MinGW\bin\g++.exe   -DQT_CORE_LIB -DQT_NO_DE
BUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REENTRANT -Dvlc_qt_core_EXPORTS -std=c++
11 @CMakeFiles/vlc-qt-core.dir/includes_CXX.rsp   -o CMakeFiles\vlc-qt-core.dir\
Error.cpp.obj -c D:\vlc-qt-master\src\core\Error.cpp
[ 20%] Building CXX object src/core/CMakeFiles/vlc-qt-core.dir/Instance.cpp.obj
cd /d D:\buildOutput\src\core && C:\MinGW\bin\g++.exe   -DQT_CORE_LIB -DQT_NO_DE
BUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REENTRANT -Dvlc_qt_core_EXPORTS -std=c++
11 @CMakeFiles/vlc-qt-core.dir/includes_CXX.rsp   -o CMakeFiles\vlc-qt-core.dir\
Instance.cpp.obj -c D:\vlc-qt-master\src\core\Instance.cpp
[ 22%] Building CXX object src/core/CMakeFiles/vlc-qt-core.dir/Media.cpp.obj
cd /d D:\buildOutput\src\core && C:\MinGW\bin\g++.exe   -DQT_CORE_LIB -DQT_NO_DE
BUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REENTRANT -Dvlc_qt_core_EXPORTS -std=c++
11 @CMakeFiles/vlc-qt-core.dir/includes_CXX.rsp   -o CMakeFiles\vlc-qt-core.dir\
Media.cpp.obj -c D:\vlc-qt-master\src\core\Media.cpp
[ 25%] Building CXX object src/core/CMakeFiles/vlc-qt-core.dir/MediaList.cpp.obj

cd /d D:\buildOutput\src\core && C:\MinGW\bin\g++.exe   -DQT_CORE_LIB -DQT_NO_DE
BUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REENTRANT -Dvlc_qt_core_EXPORTS -std=c++
11 @CMakeFiles/vlc-qt-core.dir/includes_CXX.rsp   -o CMakeFiles\vlc-qt-core.dir\
MediaList.cpp.obj -c D:\vlc-qt-master\src\core\MediaList.cpp
[ 28%] Building CXX object src/core/CMakeFiles/vlc-qt-core.dir/MediaListPlayer.c
pp.obj
cd /d D:\buildOutput\src\core && C:\MinGW\bin\g++.exe   -DQT_CORE_LIB -DQT_NO_DE
BUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REENTRANT -Dvlc_qt_core_EXPORTS -std=c++
11 @CMakeFiles/vlc-qt-core.dir/includes_CXX.rsp   -o CMakeFiles\vlc-qt-core.dir\
MediaListPlayer.cpp.obj -c D:\vlc-qt-master\src\core\MediaListPlayer.cpp
[ 31%] Building CXX object src/core/CMakeFiles/vlc-qt-core.dir/MediaPlayer.cpp.o
bj
cd /d D:\buildOutput\src\core && C:\MinGW\bin\g++.exe   -DQT_CORE_LIB -DQT_NO_DE
BUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REENTRANT -Dvlc_qt_core_EXPORTS -std=c++
11 @CMakeFiles/vlc-qt-core.dir/includes_CXX.rsp   -o CMakeFiles\vlc-qt-core.dir\
MediaPlayer.cpp.obj -c D:\vlc-qt-master\src\core\MediaPlayer.cpp
[ 34%] Building CXX object src/core/CMakeFiles/vlc-qt-core.dir/MetaManager.cpp.o
bj
cd /d D:\buildOutput\src\core && C:\MinGW\bin\g++.exe   -DQT_CORE_LIB -DQT_NO_DE
BUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REENTRANT -Dvlc_qt_core_EXPORTS -std=c++
11 @CMakeFiles/vlc-qt-core.dir/includes_CXX.rsp   -o CMakeFiles\vlc-qt-core.dir\
MetaManager.cpp.obj -c D:\vlc-qt-master\src\core\MetaManager.cpp
[ 37%] Building CXX object src/core/CMakeFiles/vlc-qt-core.dir/Video.cpp.obj
cd /d D:\buildOutput\src\core && C:\MinGW\bin\g++.exe   -DQT_CORE_LIB -DQT_NO_DE
BUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REENTRANT -Dvlc_qt_core_EXPORTS -std=c++
11 @CMakeFiles/vlc-qt-core.dir/includes_CXX.rsp   -o CMakeFiles\vlc-qt-core.dir\
Video.cpp.obj -c D:\vlc-qt-master\src\core\Video.cpp
[ 40%] Building CXX object src/core/CMakeFiles/vlc-qt-core.dir/VideoMemoryStream
.cpp.obj
cd /d D:\buildOutput\src\core && C:\MinGW\bin\g++.exe   -DQT_CORE_LIB -DQT_NO_DE
BUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REENTRANT -Dvlc_qt_core_EXPORTS -std=c++
11 @CMakeFiles/vlc-qt-core.dir/includes_CXX.rsp   -o CMakeFiles\vlc-qt-core.dir\
VideoMemoryStream.cpp.obj -c D:\vlc-qt-master\src\core\VideoMemoryStream.cpp
In file included from C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc_common.h:635:0,
                 from C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc/plugins/vlc_fourc
c.h:27,
                 from D:/vlc-qt-master/src/core/VideoMemoryStream.h:37,
                 from D:\vlc-qt-master\src\core\VideoMemoryStream.cpp:25:
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc_arrays.h: In function 'char** vlc_dicti
onary_all_keys(const vlc_dictionary_t*)':
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc_arrays.h:510:58: error: 'strdup' was no
t declared in this scope
             ppsz_ret[count++] = strdup( p_entry->psz_key );
                                                          ^
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc_arrays.h: In function 'void __vlc_dicti
onary_insert(vlc_dictionary_t*, const char*, void*, bool)':
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc_arrays.h:527:40: error: 'strdup' was no
t declared in this scope
     p_entry->psz_key = strdup( psz_key );
                                        ^
In file included from C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc/plugins/vlc_fourc
c.h:27:0,
                 from D:/vlc-qt-master/src/core/VideoMemoryStream.h:37,
                 from D:\vlc-qt-master\src\core\VideoMemoryStream.cpp:25:
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc_common.h: In function 'char* xstrdup(co
nst char*)':
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc_common.h:892:28: error: 'strdup' was no
t declared in this scope
     char *ptr = strdup (str);
                            ^
src\core\CMakeFiles\vlc-qt-core.dir\build.make:344: recipe for target 'src/core/
CMakeFiles/vlc-qt-core.dir/VideoMemoryStream.cpp.obj' failed
mingw32-make[2]: *** [src/core/CMakeFiles/vlc-qt-core.dir/VideoMemoryStream.cpp.
obj] Error 1
mingw32-make[2]: Leaving directory 'D:/buildOutput'
CMakeFiles\Makefile2:144: recipe for target 'src/core/CMakeFiles/vlc-qt-core.dir
/all' failed
mingw32-make[1]: *** [src/core/CMakeFiles/vlc-qt-core.dir/all] Error 2
mingw32-make[1]: Leaving directory 'D:/buildOutput'
Makefile:129: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by ntadej** [comment]
Very interesting. Can you try with sdk provided with windows packages (7z files for example), not from source archive. I didn't have any problems with mingw in the last few years.

**Comment by TheBinary001** [comment]
Thanks ntadej,

I changed vlc-2.2.1-win32. It's still 2 errors. So I download old vlc-2.0.8, it's successful.

So mingw32-make  gives 2 errors in: vlc-2.2.0 and vlc-2.2.1 win32.
There is no error with vlc-2.0.8. It's 1 warning of duplicated code.

**Comment by ntadej** [comment]
The errors shouldn't be there on latest VLC (warnings are OK). Unfortunately I can't help you much with it.

**Comment by TheBinary001** [comment]
Hi ntadej,

My player is cracked when run in Qt release mode with new library files.

new function is not working.
New added codes are as follow:

/* Audio.h file */

public slots:	
    void setChannel(int channel);
	
public:
    int channel() const;
	


/* Audio.cpp file */

int VlcAudio::channel() const
{
    int channel = -1;
    if (_vlcMediaPlayer) {
        channel = libvlc_audio_get_channel(_vlcMediaPlayer);
        VlcError::showErrmsg();
    }

    return channel;
}

void VlcAudio::setChannel(int channel)
{
    if (_vlcMediaPlayer) {
        // Don't change if channel is the same
        if (channel != VlcAudio::channel()) {
            libvlc_audio_set_channel(_vlcMediaPlayer, channel);
            VlcError::showErrmsg();
        }
    }
}

Thanks.

**Comment by ntadej** [comment]
There are some major build changes in latest master so I'm closing this.
