### ISSUE TITLE
100% CPU Usage using VLCQt 0.11 in qml

### ISSUE THREAD

**Issue by delavadiya** [vlc-qt/vlc-qt#102]
Hi, I used your vlc-qt library and import VLCQt 0.11 in qml file. When I played hd video in qml application it takes 100% cpu usage. However, vlc-qt widget application only takes 40-45% cpu usage to play hd video. Is it normal that  QML vlc-qt application takes high cpu usage?

My system specifications:
windows7 32-bit
Intel core 2 duo
2GB RAM

**Comment by ntadej** [comment]
Which Qt version do you use? MinGW or MSVC? If Qt 5.4 or older, OpenGL or ANGLE version?

**Comment by delavadiya** [comment]
I am using Qt 5.5.0 MinGW 32bit.
I installed latest intel graphics media accelerated driver but OpenGL Extension Viewer shows opengl version 1.1 and I don't know by default Qt creator 3.4.2 which ANGLE version used.

![capture](https://cloud.githubusercontent.com/assets/12670109/9163200/b9e8dfbe-3f66-11e5-970a-0b7f61b6e932.PNG)

DirectX diagnostic tool information:

![capture1](https://cloud.githubusercontent.com/assets/12670109/9163405/68325aaa-3f67-11e5-87be-6b764aaadfab.PNG)

**Comment by ntadej** [comment]
MinGW may have poorer performance than Qt 5.5 MSVC, as it only uses OpenGL (as far as I know). MSVC can decide to use ANGLE (DirectX wrapper), which supposedly works a bit better. Generally widgets work faster than QML.

**Comment by delavadiya** [comment]
I think you are right that MinGW is not work properlly with ANGLE. I found on internet that ANGLE is not made for compile with MinGW. So last option is to try Qt 5.5 with MSVC with ANGLE.
I will install Qt 5.5 MSVC and check the performance and I will feedback you. 
Thanks for your valuable reply.

**Comment by delavadiya** [comment]
I tried Qt 5.5 with MSVC and performance of VLCQt 0.11 2times improved compare to MinGW.
But weird thing is that player cannot play .wmv file(Windows Wildlife.wmv sample video).

**Comment by ntadej** [comment]
There seems to be a limitation, that wmv files currently cannot be displayed using QML.
