### ISSUE TITLE
How can I fix crash error of new add function after rebuild library?

### ISSUE THREAD

**Issue by TheBinary001** [vlc-qt/vlc-qt#103]
Hi ntadej,

I add a new function of audio selection in vlc-qt.
New added codes are as follow:
/* Audio.h file */
public slots:

void setChannel(int channel);
public:
int channel() const;

/* Audio.cpp file */
int VlcAudio::channel() const
{
int channel = -1;
if (_vlcMediaPlayer) {
channel = libvlc_audio_get_channel(_vlcMediaPlayer);
VlcError::showErrmsg();
}
return channel;
}

void VlcAudio::setChannel(int channel)
{
if (_vlcMediaPlayer) {
// Don't change if channel is the same
if (channel != VlcAudio::channel()) {
libvlc_audio_set_channel(_vlcMediaPlayer, channel);
VlcError::showErrmsg();
}
}
}

I reconfigure and rebuild your library. 
My player that call new added function is cracked when run in Qt release mode with new library files.
new function is not worked.
Thanks

**Comment by ntadej** [comment]
Probably you need to set channel after playback starts. I have not looked into this feature yet.

**Comment by TheBinary001** [comment]
Thanks your reply. I hope you add audio channel selection and fix error for debugging mode and crack error when qt program with vlc-qt closed.

**Comment by TheBinary001** [comment]
Thanks your reply. I hope you add audio channel selection and fix error for debugging mode and crack error when qt program with vlc-qt closed.

**Comment by ntadej** [comment]
The functionality you needed was added with #99.
