### ISSUE TITLE
App crushed when i use 4 instance and 4 players

### ISSUE THREAD

**Issue by KrepishRU** [vlc-qt/vlc-qt#104]
Hello. I use QtCreator based on 5.3.2 . Vlc-qt library 10 for mingv32. its work fine, but when i add 4 instance and use 4 players then open media by RTSP protocol (all just like in example DemoPlayer.pro) my app sometimes work well, but mostly crushed. dont know what to do :)

**Comment by ntadej** [comment]
Do you need 4 instances? Why not 1 instance and 4 players?

Can you post debug log?

**Comment by KrepishRU** [comment]
hello again . Unfortunately i cant run my app in debug mode cause i got QWidget: Must construct a QApplication before a QWidget (its about WidgetVidoe) only in relise mode running :( 4 inst where using cuase i just saw this code in example DemoPlayer. But i have just compile my code with 1 inst and 4 players. Same situation. Maeby its cause VLC trying to change my system color schema (i use Windows 7 ) to simple and failure...I compile my own lib by guide. now i used liblvc-qt 0.6.1 and VLc 2.0.2 got same trouble . But when i run my app as Administrator + WinXP Sp3 mode it just change my color schema to simple and work fine ......Sorry for my bad english by the way :)

**Comment by ntadej** [comment]
Debug version should work. I just recently tested all examples with both MinGW and MSVC. Please, try using latest master (there are nightly builds on AppVeyor).
