### ISSUE TITLE
Error in `...': realloc(): invalid pointer

### ISSUE THREAD

**Issue by aralex** [vlc-qt/vlc-qt#106]
Hello Tadej!
I'm trying to use a fresh version of vlc-qt by different ways with the same result. The test program of the library fails with a message "*** Error in `./VLC-Qt': realloc(): invalid pointer: 0x00007f45b83ac0e0 ***". An example program "simple-player" fails with similar message. I have this result on both ways: using ready DEB-packages and cloned GitHub repository of vlc-qt. My OS is Linux Mint 17.2 x64 (based on Ubuntu 14.04 LTS). Compiler is GCC 4.8.2.
Ready to help You in solving of the problem!

**Comment by ntadej** [comment]
Do you use Qt 4 or 5? If 5 is the answer, you may need to regenerate VLC cache. This is a known issue on Debian based distributions.

**Comment by aralex** [comment]
I use Qt 5.4.2. Tell Me please, how can I regenerate VLC cache?

**Comment by ntadej** [comment]
Backup `/usr/lib/vlc/plugins/plugins*.dat` then run as root
```
/usr/lib/vlc/vlc-cache-gen -f /usr/lib/vlc/plugins/
```

**Comment by aralex** [comment]
Thank You! The problem has gone!
