### ISSUE TITLE
building the binaries files (*.dll.a) from add audio channel support source code)

### ISSUE THREAD

**Issue by TheBinary001** [vlc-qt/vlc-qt#109]
Hi  ntadej,

Thank you for your new Add audio channel support function to source. (closes #99) 

So I try to build new dll.a files from your new sources.
configure and generate are ok in cmake3.3. But when I run mingw32-make, mingw32-make: *** [all] Error 2
my system is Windows7 32bit, vlc 2.0.8, Qt 5.4, 

So I use vlc-qt-0.10.0 source zip and replace with new Audio.h, Auido.cpp and Enums.h from audio channel version. configure and generate are ok in cmake3.3. mingw32-make is also [100%] Built.

Testing Qt C++ my Player project with new library files
	copy new libvlc-qt.dll.a, libvlc-qt-widgets.dll.a, libvlc-qt-widgets.dll.a to my lib folder
	copy new Audio.h, Enums.h files to my include folder
	
	add new audio change function in my Qt c++ project
	
	VlcAudio *audio = new VlcAudio(_player);
    qDebug() << audio->channel();
    audio->setChannel(Vlc::Left);
    qDebug() << audio->channel();
	
	clean all and rebuild project. Qt show 4 error as follow:
	E:\proVLC\proVLC\provlcplayer.cpp:-1: error: undefined reference to `_imp___ZNK8VlcAudio7channelEv'
	E:\proVLC\proVLC\provlcplayer.cpp:-1: error: undefined reference to `_imp___ZN8VlcAudio10setChannelEN3Vlc12AudioChannelE'
	:-1: error: release/provlcplayer.o: bad reloc address 0x20 in section `.text$_ZN7QStringD1Ev[__ZN7QStringD1Ev]'
	collect2.exe:-1: error: error: ld returned 1 exit status
	
	so I comment new added audio codes and rebuild project and run. It run successfully and project is working and player is ok.

How can I fix it? OR 
Where can I download new libvlc-qt.dll.a, libvlc-qt-widgets.dll.a, libvlc-qt-widgets.dll.a files with audio channel features?

Thanks.

**Comment by ntadej** [comment]
You can not just replace headers in old release. There were some changes between 0.10 and latest master. There are latest nightly builds in [AppVeyor](https://ci.appveyor.com/project/ntadej/vlc-qt).
