### ISSUE TITLE
Where is simple-player source code for Latest vlc-qt Library?

### ISSUE THREAD

**Issue by isocollection** [vlc-qt/vlc-qt#110]
Hello,
I'm very happy when I found your vlc-qt library. I want to create a customized vlc sample player. VLC is my favorite player. Your work is the best contribution for  Qt C++ developers. vlc-qt library has many features that I want.
    libvlc instance and player
    single file and playlist playback
    audio and video control
    metadata management
I start and test your sample-demo player qt project with vlc-qt library. Player can run successfully on my computer. I got your all source from VLC-Qt 0.10.0. But it's lack of audio channel selection (left, right, stereo feature). 

Now I found your latest binary vlc-qt version that support audio feature on  appveyor.com. It's binary files only. I tried to develop and run a new sample player with latest library. But It can't run and cracked. I tried several times and many ways to run it. it's not successful.

So I would like to know where can I download your Qt C++ sample player Qt source code for latest vcl-qt library? https://github.com/vlc-qt/examples is the old library sample source code.

My computer has windows 7 platform 32bit and I used Qt C++ 5.x MinGW version.
I hope you may share the sample domo player source code.

regards
newbie Qt C++  student

**Comment by ntadej** [comment]
There is no specific sample for audio channel selection.

Make sure you try to change audio channels after the media starts.

**Comment by isocollection** [comment]
Thank you for your reply.

You uploaded only VLC-Qt_Test_1.0.0 on AppVeyor that contained VLC-Qt.exe and some run time VLC library files. There is no source code of this VLC-Qt Test in it.

**Comment by ntadej** [comment]
It is in this repository in tests folder.
