### ISSUE TITLE
building binaries files with 2 errors

### ISSUE THREAD

**Issue by itman2200** [vlc-qt/vlc-qt#111]
Hello and thank you for your contribution of  open source library.

I compile VLC-Qt, your repository vlc-qt-0.10.0 and build binary files. 
mingw32-make: *** [all] Error 2. I use vlc-2-2-1-win32. So I change to other version. It gives error.
Building is 100% successfully done with vlc-2-0-8-win32. When I check vlc player's include folder and its files, there are some differences in its versions.

Then I try to build latest repository. mingw32-make can't build and gives 2 errors. I change to different vlc versions but errors still exists.

logs 
C:\new\dll11>mingw32-make
E:\cmake33\bin\cmake.exe -HC:\new\vlc-qt-0.11.0 -BC:\new\dll11 --check-build-sys
tem CMakeFiles\Makefile.cmake 0
E:\cmake33\bin\cmake.exe -E cmake_progress_start C:\new\dll11\CMakeFiles C:\new\
dll11\CMakeFiles\progress.marks
mingw32-make -f CMakeFiles\Makefile2 all
mingw32-make[1]: Entering directory 'C:/new/dll11'
mingw32-make -f src\core\CMakeFiles\Core_automoc.dir\build.make src/core/CMakeFi
les/Core_automoc.dir/depend
mingw32-make[2]: Entering directory 'C:/new/dll11'
E:\cmake33\bin\cmake.exe -E cmake_depends "MinGW Makefiles" C:\new\vlc-qt-0.11.0
 C:\new\vlc-qt-0.11.0\src\core C:\new\dll11 C:\new\dll11\src\core C:\new\dll11\s
rc\core\CMakeFiles\Core_automoc.dir\DependInfo.cmake --color=
Scanning dependencies of target Core_automoc
mingw32-make[2]: Leaving directory 'C:/new/dll11'
mingw32-make -f src\core\CMakeFiles\Core_automoc.dir\build.make src/core/CMakeFi
les/Core_automoc.dir/build
mingw32-make[2]: Entering directory 'C:/new/dll11'
[  2%] Automatic moc, uic and rcc for target Core
cd /d C:\new\dll11\src\core && E:\cmake33\bin\cmake.exe -E cmake_autogen C:/new/
dll11/src/core/CMakeFiles/Core_automoc.dir/ ""
Generating moc_Audio.cpp
Generating moc_Enums.cpp
Generating moc_Equalizer.cpp
Generating moc_Instance.cpp
Generating moc_Media.cpp
Generating moc_MediaList.cpp
Generating moc_MediaListPlayer.cpp
Generating moc_MediaPlayer.cpp
Generating moc_Video.cpp
mingw32-make[2]: Leaving directory 'C:/new/dll11'
[  2%] Built target Core_automoc
mingw32-make -f src\core\CMakeFiles\Core.dir\build.make src/core/CMakeFiles/Core
.dir/depend
mingw32-make[2]: Entering directory 'C:/new/dll11'
[  5%] Generating ../../platform/windows/core.obj
cd /d C:\new\vlc-qt-0.11.0\platform\windows && C:\MinGW\bin\windres.exe -i C:/ne
w/dll11/platform/windows/core.rc -o C:/new/dll11/platform/windows/core.obj
E:\cmake33\bin\cmake.exe -E cmake_depends "MinGW Makefiles" C:\new\vlc-qt-0.11.0
 C:\new\vlc-qt-0.11.0\src\core C:\new\dll11 C:\new\dll11\src\core C:\new\dll11\s
rc\core\CMakeFiles\Core.dir\DependInfo.cmake --color=
Scanning dependencies of target Core
mingw32-make[2]: Leaving directory 'C:/new/dll11'
mingw32-make -f src\core\CMakeFiles\Core.dir\build.make src/core/CMakeFiles/Core
.dir/build
mingw32-make[2]: Entering directory 'C:/new/dll11'
[  8%] Building CXX object src/core/CMakeFiles/Core.dir/Audio.cpp.obj
cd /d C:\new\dll11\src\core && C:\MinGW\bin\g++.exe   -DCore_EXPORTS -DQT_CORE_L
IB -DQT_NO_DEBUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REENTRANT -std=c++11 @CMake
Files/Core.dir/includes_CXX.rsp   -o CMakeFiles\Core.dir\Audio.cpp.obj -c C:\new
\vlc-qt-0.11.0\src\core\Audio.cpp
In file included from C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc/plugins/vlc_commo
n.h:709:0,
                 from C:\new\vlc-qt-0.11.0\src\core\Audio.cpp:30:
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc/plugins/vlc_arrays.h: In function 'char
** vlc_dictionary_all_keys(const vlc_dictionary_t*)':
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc/plugins/vlc_arrays.h:515:58: error: 'st
rdup' was not declared in this scope
             ppsz_ret[count++] = strdup( p_entry->psz_key );
                                                          ^
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc/plugins/vlc_arrays.h: In function 'void
 __vlc_dictionary_insert(vlc_dictionary_t*, const char*, void*, bool)':
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc/plugins/vlc_arrays.h:532:40: error: 'st
rdup' was not declared in this scope
     p_entry->psz_key = strdup( psz_key );
                                        ^
In file included from C:\new\vlc-qt-0.11.0\src\core\Audio.cpp:30:0:
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc/plugins/vlc_common.h: In function 'void
* vlc_memalign(size_t, size_t)':
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc/plugins/vlc_common.h:942:51: error: 'po
six_memalign' was not declared in this scope
     if (unlikely(posix_memalign(&base, align, size)))
                                                   ^
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc/plugins/vlc_common.h:116:44: note: in d
efinition of macro 'unlikely'
 #   define unlikely(p) __builtin_expect(!!(p), 0)
                                            ^
src\core\CMakeFiles\Core.dir\build.make:69: recipe for target 'src/core/CMakeFil
es/Core.dir/Audio.cpp.obj' failed
mingw32-make[2]: *** [src/core/CMakeFiles/Core.dir/Audio.cpp.obj] Error 1
mingw32-make[2]: Leaving directory 'C:/new/dll11'
CMakeFiles\Makefile2:144: recipe for target 'src/core/CMakeFiles/Core.dir/all' f
ailed
mingw32-make[1]: *** [src/core/CMakeFiles/Core.dir/all] Error 2
mingw32-make[1]: Leaving directory 'C:/new/dll11'
Makefile:129: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

C:\new\dll11>

How can I fix it?

**Comment by itman2200** [comment]
make33-gui logs are as follow:

VLC-Qt: You are compiling VLC-Qt 0.90.0

The C compiler identification is GNU 4.8.1
The CXX compiler identification is GNU 4.8.1
Check for working C compiler: C:/MinGW/bin/gcc.exe
Check for working C compiler: C:/MinGW/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/MinGW/bin/g++.exe
Check for working CXX compiler: C:/MinGW/bin/g++.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
VLC-Qt: Build with Qt5
VLC-Qt: Build with OpenGL ES2: OFF
Found LibVLC include-dir path: C:/Program Files/VideoLAN/VLC/sdk/include
Found LibVLC library path:C:/Program Files/VideoLAN/VLC/libvlc.dll
Found LibVLCcore library path:C:/Program Files/VideoLAN/VLC/libvlccore.dll
VLC-Qt: Build statically: OFF

VLC-Qt: Build tests: OFF

Configuring done
Generating done

**Comment by ntadej** [comment]
Which version of MinGW and Qt are you using?

**Comment by itman2200** [comment]
mingw491_32, Qt5.4.0, cmake3.3.0, vlc 2.0.8, win32bit

**Comment by ntadej** [comment]
Qt 5.4 is built with MinGW 4.9.1. It was the reference compiler I used. Are there any reasons you do not use Qt 5.5 and MinGW 4.9.2 which are latest available?

**Comment by itman2200** [comment]
Thanks. I'll try to build it with Qt 5.5.

**Comment by ntadej** [comment]
Also make sure that you build with mingw console.

**Comment by itman2200** [comment]
Qt 5.4 built with MinGW 4.9.1 cmake3.3.0 log

VLC-Qt: You are compiling VLC-Qt 0.90.0

The C compiler identification is GNU 4.9.1
The CXX compiler identification is GNU 4.9.1
Check for working C compiler: C:/Qt/Qt5.4.0/Tools/mingw491_32/bin/gcc.exe
Check for working C compiler: C:/Qt/Qt5.4.0/Tools/mingw491_32/bin/gcc.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: C:/Qt/Qt5.4.0/Tools/mingw491_32/bin/g++.exe
Check for working CXX compiler: C:/Qt/Qt5.4.0/Tools/mingw491_32/bin/g++.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
VLC-Qt: Build with Qt5
VLC-Qt: Build with OpenGL ES2: OFF
Found LibVLC include-dir path: C:/Program Files/VideoLAN/VLC/sdk/include
Found LibVLC library path:C:/Program Files/VideoLAN/VLC/libvlc.dll
Found LibVLCcore library path:C:/Program Files/VideoLAN/VLC/libvlccore.dll
VLC-Qt: Build statically: OFF

VLC-Qt: Build tests: OFF

Configuring done
Generating done

**Comment by itman2200** [comment]
mingw32-make with error 2 log:

C:\new\dll11>mingw32-make
E:\cmake33\bin\cmake.exe -HC:\new\vlc-qt-0.11.0 -BC:\new\dll11 --check-build-sys
tem CMakeFiles\Makefile.cmake 0
E:\cmake33\bin\cmake.exe -E cmake_progress_start C:\new\dll11\CMakeFiles C:\new\
dll11\CMakeFiles\progress.marks
mingw32-make -f CMakeFiles\Makefile2 all
mingw32-make[1]: Entering directory 'C:/new/dll11'
mingw32-make -f src\core\CMakeFiles\Core_automoc.dir\build.make src/core/CMakeFi
les/Core_automoc.dir/depend
mingw32-make[2]: Entering directory 'C:/new/dll11'
E:\cmake33\bin\cmake.exe -E cmake_depends "MinGW Makefiles" C:\new\vlc-qt-0.11.0
 C:\new\vlc-qt-0.11.0\src\core C:\new\dll11 C:\new\dll11\src\core C:\new\dll11\s
rc\core\CMakeFiles\Core_automoc.dir\DependInfo.cmake --color=
Scanning dependencies of target Core_automoc
mingw32-make[2]: Leaving directory 'C:/new/dll11'
mingw32-make -f src\core\CMakeFiles\Core_automoc.dir\build.make src/core/CMakeFi
les/Core_automoc.dir/build
mingw32-make[2]: Entering directory 'C:/new/dll11'
[  2%] Automatic moc, uic and rcc for target Core
cd /d C:\new\dll11\src\core && E:\cmake33\bin\cmake.exe -E cmake_autogen C:/new/
dll11/src/core/CMakeFiles/Core_automoc.dir/ ""
Generating moc_Audio.cpp
Generating moc_Enums.cpp
Generating moc_Equalizer.cpp
Generating moc_Instance.cpp
Generating moc_Media.cpp
Generating moc_MediaList.cpp
Generating moc_MediaListPlayer.cpp
Generating moc_MediaPlayer.cpp
Generating moc_Video.cpp
mingw32-make[2]: Leaving directory 'C:/new/dll11'
[  2%] Built target Core_automoc
mingw32-make -f src\core\CMakeFiles\Core.dir\build.make src/core/CMakeFiles/Core
.dir/depend
mingw32-make[2]: Entering directory 'C:/new/dll11'
[  5%] Generating ../../platform/windows/core.obj
cd /d C:\new\vlc-qt-0.11.0\platform\windows && C:\Qt\Qt5.4.0\Tools\mingw491_32\b
in\windres.exe -i C:/new/dll11/platform/windows/core.rc -o C:/new/dll11/platform
/windows/core.obj
E:\cmake33\bin\cmake.exe -E cmake_depends "MinGW Makefiles" C:\new\vlc-qt-0.11.0
 C:\new\vlc-qt-0.11.0\src\core C:\new\dll11 C:\new\dll11\src\core C:\new\dll11\s
rc\core\CMakeFiles\Core.dir\DependInfo.cmake --color=
Scanning dependencies of target Core
mingw32-make[2]: Leaving directory 'C:/new/dll11'
mingw32-make -f src\core\CMakeFiles\Core.dir\build.make src/core/CMakeFiles/Core
.dir/build
mingw32-make[2]: Entering directory 'C:/new/dll11'
[  8%] Building CXX object src/core/CMakeFiles/Core.dir/Audio.cpp.obj
cd /d C:\new\dll11\src\core && C:\Qt\Qt5.4.0\Tools\mingw491_32\bin\g++.exe   -DC
ore_EXPORTS -DQT_CORE_LIB -DQT_NO_DEBUG -DQT_SHARED -DVLCQT_CORE_LIBRARY -D_REEN
TRANT -std=c++11 @CMakeFiles/Core.dir/includes_CXX.rsp   -o CMakeFiles\Core.dir\
Audio.cpp.obj -c C:\new\vlc-qt-0.11.0\src\core\Audio.cpp
In file included from C:\new\vlc-qt-0.11.0\src\core\Audio.cpp:30:0:
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc/plugins/vlc_common.h: In function 'void
* vlc_memalign(size_t, size_t)':
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc/plugins/vlc_common.h:942:51: error: 'po
six_memalign' was not declared in this scope
     if (unlikely(posix_memalign(&base, align, size)))
                                                   ^
C:/PROGRA~1/VideoLAN/VLC/sdk/include/vlc/plugins/vlc_common.h:116:44: note: in d
efinition of macro 'unlikely'
 #   define unlikely(p) __builtin_expect(!!(p), 0)
                                            ^
src\core\CMakeFiles\Core.dir\build.make:69: recipe for target 'src/core/CMakeFil
es/Core.dir/Audio.cpp.obj' failed
mingw32-make[2]: *** [src/core/CMakeFiles/Core.dir/Audio.cpp.obj] Error 1
mingw32-make[2]: Leaving directory 'C:/new/dll11'
CMakeFiles\Makefile2:144: recipe for target 'src/core/CMakeFiles/Core.dir/all' f
ailed
mingw32-make[1]: *** [src/core/CMakeFiles/Core.dir/all] Error 2
mingw32-make[1]: Leaving directory 'C:/new/dll11'
makefile:129: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

C:\new\dll11>

**Comment by itman2200** [comment]
Thank you for your advice! Qt 5.5 is downloading now.

**Comment by itman2200** [comment]
Today I use Qt 5.5 and MinGW 4.9.2. It also shows 2 errors in minGW32-make console. So I downloaded your latest binaries. Qt sample project is not working with them.

Your vlc qt 10 source can be built successfully and binary files can run well on the computer.
Your vlc qt 10 binary files are also run successfully on my pc. But there is no equalizer feature in this version.

So you may upload latest binary files again (if possible). The files may damage or something...

**Comment by ntadej** [comment]
1.0 beta 1 will be released soon, but if it doesn't work now, it won't work afterwards.

This is the build that added audio channel support and it passed:
https://ci.appveyor.com/project/ntadej/vlc-qt/build/1.0.0.53/job/tvosq6vyvefegri2

There is not much I can do. It works on my PC, it works on AppVeyor. Maybe go through AppVeyor build process if you do anything different than me.

**Comment by itman2200** [comment]
Thank you for your contribution.

**Comment by jps05** [comment]
I got the same error as described above with the following configuration:
Qt5.9.1
MinGW 5.3.0
vlc-2.2.6
vlc-qt-1.2
started build-process from MinGW-console

**Comment by jps05** [comment]
ok, when I copy the Include-files from your libvlc-headers-folder to the vlc-2.2.6-folder and replacing the original ones, everything is working fine. Is that the right way to do it?
