### ISSUE TITLE
get available plugins?

### ISSUE THREAD

**Issue by dakom** [vlc-qt/vlc-qt#112]
Two part question :)

1) Is there an easy way to get a list of available plugins? (bonus if it can list which ones are loaded!)

2) If not- would it be easy to add a VlcCommon::getPluginPath()? Since plugins must follow a specific naming convention- one could just list the files from that location which match that pattern

**Comment by ntadej** [comment]
Why do you need this information?

You can get list of audio and video filters directly from libvlc
https://www.videolan.org/developers/vlc/doc/doxygen/html/group__libvlc__core.html#gaaeb3d86da9e6544ef4894b9f0a2c411f

I can wrap this for you if it is useful.

**Comment by dakom** [comment]
Yeah- would be cool if you could add that and it's not too much trouble :)

At the moment it's just to see which dlls are actually used and what I really need to package, without relying on DependancyWalker, but it also helps some debugging cases

**Comment by dakom** [comment]
Thanks :)
