### ISSUE TITLE
stretched playback video to Fit screen (not keep aspect ratio)

### ISSUE THREAD

**Issue by itman2200** [vlc-qt/vlc-qt#113]
Hello, 
I add a widget on my form named as video. 

my widget is resized according to my computer screen. So I also want to resize playback video to fit with my widget (not keep aspect ratio). I found enum ratio.
ui->video->setAspectRatio(Vlc::Original); These ratio and scales are fixed predefined ratio. 

My widget may resize depend upon  computer's various screen resolution and ratio. How can I stretch playback video to Fit the my widget?

**Comment by ntadej** [comment]
I think this is currently not possible. Is there an option available in VLC?

**Comment by zeal18** [comment]
It is possible if you will paint image yourself like vlc-qt-qml does
