### ISSUE TITLE
RTSP reconnect

### ISSUE THREAD

**Issue by KrepishRU** [vlc-qt/vlc-qt#115]
Hello =) anybody know how to reconnect to RTSP by VLC? i got video registrator on Network . When i start my app all fine. But when i just brake a network connection or restart registrator - all gonna freeze. i was trying to reconnect player with media but nothing.

**Comment by ntadej** [comment]
Do you listen to any events from player? Maybe you get a specific event and you can programatically reconnect.

**Comment by KrepishRU** [comment]
i gues i just starting to replay early. Registrator have delay to start send me RTSP frame for my command PLAY =) about 3 seconds delay. If i just create new media and open player after 3 second - work fine=)
