### ISSUE TITLE
Must construct a QApplication before a QWidget

### ISSUE THREAD

**Issue by mehdidante** [vlc-qt/vlc-qt#116]
i'm using visual studio 2013 . i created a Widget in qt designer and used promote to promote it to VlcWidgetVideo class . i have done nothing else but when i run i get this error : 
QWidget: Must construct a QApplication before a QWidget
The program '[3920] qt_vlc2.exe' has exited with code 1 (0x1).

everything is generated by qt and works but when i add your WidgetVideo i get error .
by the way when i downloaded binary files , the name of the file was WidgetVideo.h but the class name is VlcWidgetVideo so i have changed the name of it to vlcWidgetVideo .

**Comment by ntadej** [comment]
Make sure you use correct libraries. For debug build, use debug libraries, for release build, use release ones.

**Comment by mehdidante** [comment]
ok . thanks . that was correct . it works in release mode . i have to compile qt-vlc from source to get the debug dlls (hope to compile without error ) . thanks again .

**Comment by ntadej** [comment]
Beta was just released today. There should be debug libraries attached for Windows.

**Comment by mehdidante** [comment]
today !!! on it ...
.
.
ok thanks . its true .finally files with d suffix . this is great . by the way  i'm trying to make it work with openCV . if you know any good tutorial that would be really helpful . tnx.

**Comment by ntadej** [comment]
No, sorry, I don't know opencv

**Comment by gakwaya** [comment]
There is a repository https://github.com/kibsoft/QtMEL that mixes ffmpeg and opencv ,it may be a good reference.
