### ISSUE TITLE
setPluginPath() compile time error

### ISSUE THREAD

**Issue by arguan992** [vlc-qt/vlc-qt#117]
Hi @ ntadej
I have written the code provided by you for the simple player,but the setPluginPath method is giving the following error
main.cpp:11: error: undefined reference to `VlcCommon::setPluginPath(QString const&)'
All the code is similar to the one that you have provided. What do I need to do??

**Comment by ntadej** [comment]
It seems that you do not include correct headers or you do not link with VLC-Qt properly.

**Comment by arguan992** [comment]
I used the add library function provided by qt itself to add vlc core and qt libraries. I will post my .pro file here for you to see. Please tell me if Im doing anything wrong.
Thank you

**Comment by arguan992** [comment]
QT       += core gui

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

TARGET = mediaplayertry1
TEMPLATE = app



SOURCES += main.cpp\
        mainwindow.cpp

HEADERS  += mainwindow.h

FORMS    += mainwindow.ui

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/../libvlc-qt-0.9.0/build/src/core/release/ -lvlc-qt
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/../libvlc-qt-0.9.0/build/src/core/debug/ -lvlc-qt
else:unix: LIBS += -L$$PWD/../libvlc-qt-0.9.0/build/src/core/ -lvlc-qt

INCLUDEPATH += $$PWD/../libvlc-qt-0.9.0/build/src/core
DEPENDPATH += $$PWD/../libvlc-qt-0.9.0/build/src/core

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/../libvlc-qt-0.9.0/build/src/widgets/release/ -lvlc-qt-widgets
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/../libvlc-qt-0.9.0/build/src/widgets/debug/ -lvlc-qt-widgets
else:unix: LIBS += -L$$PWD/../libvlc-qt-0.9.0/build/src/widgets/ -lvlc-qt-widgets

INCLUDEPATH += $$PWD/../libvlc-qt-0.9.0/build/src/widgets
DEPENDPATH += $$PWD/../libvlc-qt-0.9.0/build/src/widgets

RESOURCES += \
    Resources.qrc

This is my .pro file. Please tell me where Iam going wrong. 
Thank You

**Comment by ntadej** [comment]
You are using very old version of VLC-Qt. please update to latest stable released version.

**Comment by arguan992** [comment]
Okayy Thanx!!
