### ISSUE TITLE
show VLC (Direct3D output) dialog box, how to disable it?

### ISSUE THREAD

**Issue by itman2200** [vlc-qt/vlc-qt#118]
Hi,
I created a sample player with your qt-vlc library. I opened several video (mpg, mp4 format) with it, sometimes my sample player showed VLC (Direct3D output) dialog box while it's playing a video. I think It occurred some video format file. How can I disable or hide this diallog box programmatically in Qt? I used Qt 5.4.x, Win7 32bit, vlc-qt 10.

Thanks

**Comment by ntadej** [comment]
Can you please provide:
 - a screenshot of the issue
 - a sample file that has the problem

**Comment by itman2200** [comment]
please see screenshot at attach file.
I'm sorry I can't upload video file because of large file size and very slow internet connection now. I try to upload next day.

When I use google and serach this error. It's the worst error in vlc player. I opened this video with vlc player. It showed this error again. I found so many question of this error with vlc on youtube channel
sample video from other upload is
https://www.youtube.com/watch?v=3pIIIZNvemU

**Comment by itman2200** [comment]
![vlc](https://cloud.githubusercontent.com/assets/14106245/10332073/a509e2c4-6d00-11e5-95ae-22764f3e0d4f.jpg)

**Comment by ZeroHackeR** [comment]
Did you manage to fix it? @itman2200 @ntadej

**Comment by ntadej** [comment]
This seems to be VLC bug as it also occurs on VLC player. Please, report to them.
