### ISSUE TITLE
Cannot unpause video. Stop freezes application.

### ISSUE THREAD

**Issue by RazrFalcon** [vlc-qt/vlc-qt#120]
I use "Basic player test" to show video. When I open any video - all works fine until I press stop or pause.
When I press Pause - I cannot longer unpause it. Clicking on btn didn't work at all.
When I press Stop - application just freezes and I need to kill it.

Gentoo Linux x86-64, Qt 5.4.2, VLC 2.1.5-r1 with such flags:
(X a52 alsa avcodec avformat dbus dts dvbpsi encode ffmpeg flac fontconfig gcrypt kde libnotify mp3 mpeg ncurses ogg opengl png postproc qt4 sdl svg swscale truetype udev vorbis x264 xcb xml xv -aalib -altivec -atmo -audioqueue -avahi -bidi -bluray -cdda -cddb -chromaprint -dc1394 -debug -dirac -directfb -directx -dvb -dvd -dxva2 -egl -faad -fdk -fluidsynth -gme -gnome -gnutls -growl -httpd -ieee1394 -ios-vout -jack -kate -libass -libav -libcaca -libsamplerate -libtar -libtiger -linsys -lirc -live -lua -macosx -macosx-audio -macosx-dialog-provider -macosx-eyetv -macosx-qtkit -macosx-quartztext -macosx-vout -matroska -media-library -modplug -mtp -musepack -neon -omxil -opencv -optimisememory -opus -projectm -pulseaudio -rdp -rtsp -run-as-root -samba -schroedinger -sdl-image -sftp -shout -sid -skins -speex -taglib -test -theora -tremor -twolame -upnp -v4l -vaapi -vcdx -vdpau -vlm -vnc -wma-fixed -zvbi CPU_FLAGS_X86="mmx sse" ELIBC="glibc")

Maybe I need enable something to make it works?

Application log:
VLC-Qt "0.90.0" initialised
Using libvlc version: "2.1.5 Rincewind"
libvlc Media: "/media/data/SampleVideo.mp4" Local: true
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
Fontconfig warning: FcPattern object size does not accept value "0"
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
QWidget::paintEngine: Should no longer be called
[0x7f6cb4001268] main vout display error: Failed to resize display
[0x7f6cb4001268] main vout display error: Failed to resize display <-- Stop clicked
The program has unexpectedly finished. <-- I'm killed application

**Comment by ntadej** [comment]
Can you try running in debugger? It would be good to know, if it crashes in libVLC or in VLC-Qt.

**Comment by RazrFalcon** [comment]
It freezes at:

`libvlc_media_player_stop(_vlcMediaPlayer);`

in MediaPlayer.cpp:299

In debug mode I get this errors in stdout:

`[0x983a48] main input error: ES_OUT_SET_(GROUP_)PCR  is called too late (pts_delay increased to 300 ms)`
`[0x983a48] main input error: ES_OUT_RESET_PCR called`

Video/Audio format doesn't matter.

**Comment by ntadej** [comment]
Looks like a bug in VLC to me, but I will look at it.

**Comment by ntadej** [comment]
Fixed.
