### ISSUE TITLE
looking to stream from shoutcast using vlc 

### ISSUE THREAD

**Issue by doged** [vlc-qt/vlc-qt#122]
hi, i currently have a cryptocurrency qt wallet that i have integrated tor and irc chat into, and am integrating the coins streaming shoutcast station into. id like it to use vlc and only play from the stream, not act as a media player. 

does this seem doable?

**Comment by doged** [comment]
id really like to use vlc, mainly because of its stability and non-bloatedness..

**Comment by ntadej** [comment]
Is your stream currently playable by normal VLC app?

**Comment by doged** [comment]
@ntadej yes

**Comment by ntadej** [comment]
So you can play it in your app with VLC-Qt. You do not need to display any media controls.

**Comment by doged** [comment]
that is what i was thinking. just harcode the url in.. or the .pls ?

**Comment by ntadej** [comment]
Use the same url you can successfully play in VLC as media URL. If it will be the same all the time, just hardcode it into a variable, otherwise load it with your application somehow.

**Comment by doged** [comment]
sweet. can i tag you in my repo as i work on it if i run into trouble?

**Comment by ntadej** [comment]
No problem.

Feel free to close this issue when you don't need it anymore.

**Comment by doged** [comment]
thanks!

**Comment by doged** [comment]
@ntadej take a look at https://github.com/doged/dogedsource/tree/radio

i was trying to insert the demoplayer as a tab in this qt app.. made a branch for testing it..
