### ISSUE TITLE
error when installing on ubuntu:

### ISSUE THREAD

**Issue by justinvforvendetta** [vlc-qt/vlc-qt#123]
test123@test123-VirtualBox:~$ sudo apt-get install libvlc-qt-core1 libvlc-qt-widgets1 libvlc-qt-dbg libvlc-qt-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libvlc-qt-core1
E: Unable to locate package libvlc-qt-widgets1
E: Unable to locate package libvlc-qt-dbg
E: Unable to locate package libvlc-qt-dev

**Comment by justinvforvendetta** [comment]
this was after importing key and pulling from clean archive repo

test123@test123-VirtualBox:~$ sudo apt-key adv --recv-keys --keyserver keyserver.ubuntu.com 55D8172B
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.FBUWZMz7sq --no-auto-check-trustdb --trust-model always --keyring /etc/apt/trusted.gpg --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/ntadej_ubuntu_tano-clean.gpg --keyring /etc/apt/trusted.gpg.d/ntadej_ubuntu_tano.gpg --recv-keys --keyserver keyserver.ubuntu.com 55D8172B
gpg: requesting key 55D8172B from hkp server keyserver.ubuntu.com
gpg: key 55D8172B: "Launchpad PPA for ntadej" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
test123@test123-VirtualBox:~$ sudo apt-get install libvlc-qt-core1 libvlc-qt-widgets1 libvlc-qt-dbg libvlc-qt-dev
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package libvlc-qt-core1
E: Unable to locate package libvlc-qt-widgets1
E: Unable to locate package libvlc-qt-dbg
E: Unable to locate package libvlc-qt-dev

**Comment by ntadej** [comment]
VLC-Qt 1.0 will be released today and packages are already being built.

**Comment by doged** [comment]
@ntadej i wrote you on facebook. are you at all interested in a small project, would probably only take a day, and i can pay you in btc.. just need a hand implementing a "radio tab" in a qt app i already have (and works) that plays a stream from a shoutcast server (that is already up and running as well)
