### ISSUE TITLE
VlcMediaListPlayer opens a new window (and does not play in assigned Video Widget)

### ISSUE THREAD

**Issue by micdobro** [vlc-qt/vlc-qt#126]
I would like to play a video "forever" in a loop - so I created a MediaList with one item, set the playback method into Loop (doing that with the regular player does not work; stop() and play() make the screen flicker). But to my surprise VLC instance starts in a new window... completely ignoring the Video Widget that was assigned to the explicitly created player. This sounds like a bug... as the target should be the Video Widget, not a new window instance (with all decorators & other UI bars).

**Comment by ntadej** [comment]
Is there a code I can look at?

**Comment by micdobro** [comment]
Here it comes - it is a very simple line-up that is also visible here in another issue. The ui->video widget is added in QtCreator (promoted Widget). 

```cpp
    ui->setupUi(this);
    _instance = new VlcInstance(VlcCommon::args(), this);
    _media = new VlcMedia("movie.mp4", true, _instance);
    _player = new VlcMediaPlayer(_instance);
    _player->setVideoWidget(ui->video);

    _playlist = new VlcMediaList(_instance);
    _playlist->addMedia(_media);

    _listplayer = new VlcMediaListPlayer(_player, _instance);
    _listplayer->setMediaList(_playlist);
    _listplayer->setPlaybackMode(Vlc::Loop);

    _player->setVideoWidget(ui->video);
     ui->video->setMediaPlayer(_player);
    _listplayer->play();

```

When using VlcMediaPlayer - everything works as it should.

**Comment by ntadej** [comment]
Take a look at [tests/widgets/MediaList.cpp](https://github.com/vlc-qt/vlc-qt/blob/master/tests/widgets/MediaList.cpp) and belonging ui file as it works for me.

**Comment by micdobro** [comment]
Thanks. From what I can see, the main difference comes here:

```cpp
 _listPlayer->mediaPlayer()->play(); 
```

I have just modified by source and cleaned it up (to match the example), got this (and no movie): 

```shell
libvlc Error: "No associated media descriptor" 
```
Disclaimer: using ver. 0.10

**Comment by ntadej** [comment]
Next needs to be called first for some reason. If you find a better solution, let me know.

**Comment by micdobro** [comment]
That indeed solves the problem. I will paste the correct piece here for the benefit of others. 

```cpp
    _instance = new VlcInstance(VlcCommon::args(), this);
    _player = new VlcMediaPlayer(_instance);
    _player->setVideoWidget(ui->video);

    _listplayer = new VlcMediaListPlayer(_player, _instance);

    ui->video->setMediaPlayer(_player);

    _playlist = new VlcMediaList(_instance);
    _playlist->addMedia(new VlcMedia("movie.mp4", true, _instance));

    _listplayer->setMediaList(_playlist);
    _listplayer->setPlaybackMode(Vlc::Loop);
    
      /* w/o next() nothing will be played */
    _listplayer->next();
      /* Calling play on _listplayer will result in a new window */
    _listplayer->mediaPlayer()->play();
```
