### ISSUE TITLE
[OS X] Widget Video always on top 

### ISSUE THREAD

**Issue by gavaza** [vlc-qt/vlc-qt#135]
VlcWidgetVideo always on top, even without focus.
![captura de tela 2016-02-20 as 01 05 34](https://cloud.githubusercontent.com/assets/11299390/13194368/76a1917e-d76e-11e5-8a61-31cc14c526ba.png)

The focus is on "controle de sessões", but the vlcWidgetVideo remains always on top.
Qt 5.4.0 and 1.0.1 VLC-qt on OS X.

For Windows works correctly.

**Comment by ntadej** [comment]
I do not encounter this issue on my Mac. Which graphics card is active at the moment of playback?

**Comment by gavaza** [comment]
Onboard Intel HD Graphics 3000

**Comment by ntadej** [comment]
I checked again on my Tano app and no issues there.

**Comment by ntadej** [comment]
Closing this as it can not be reproduced.
