### ISSUE TITLE
VLCQtCore.dll Entry Point Not Found

### ISSUE THREAD

**Issue by wardjk** [vlc-qt/vlc-qt#138]
I compiled and tried running simple-player.exe on two different Windows PCs but encountered the same error on both. 

The error message shown is essentially the same as the following message copied from the system log:

simple-player.exe - Entry Point Not Found : The procedure entry point ?registerNormalizedType@QMetaType@@SAHABVQByteArray@@P6AXPAX@ZP6APAX1PBX@ZHV?$QFlags@W4TypeFlag@QMetaType@@@@PBUQMetaObject@@@Z could not be located in the dynamic link library C:\Programs\libvlc-qt\VLC-Qt_1.0.1_win32_msvc2013\bin\VLCQtCore.dll. 

I started with the contents of VLC-Qt_1.0.1_win32_msvc2013.7z and performed the same steps on both PCs so I'm guessing that there is another step that must be completed such as installing dependencies or registering dlls. I didn't find an explicit procedure of how to install VLC-Qt so I assumed it was so simple it didn't need a procedure. How can this problem be solved?

**Comment by ntadej** [comment]
I forgot to explicitly note this when adding build instructions few days ago :(

If you build in Debug mode, you need to use debug dlls (ending with d) and similar for Release you use release dlls. Also, the release binaries are made using Qt 5.5.

**Comment by wardjk** [comment]
The debug build references VLCQtCored.dll and the release build references VLCQtCore.dll. For both debug and release, I compiled simple-player.exe for Qt 5.5.1. Is there something else I can look for or try?

**Comment by ntadej** [comment]
Very strange. I can try in a few days on Windows.

**Comment by suratovvlad** [comment]
Did you try to link .lib to project? Try to tell qmake in .pro that you need:
LIBS += $$files(/path/to/libs/VLCQTCored.lib) or something like this (for mingw I wrote path to libVLCQTCored.a)

**Comment by wardjk** [comment]
Yes, LIBS specified, links fine. Problem encountered only on execution.

Dependency Walker doesn't list registerNormalizedType as an exported function of VLCQtCore.dll but I see that it is in the dll.
An internet search for "registerNormalizedType" shows similar problems for others but I haven't yet found the solution. I suspect a Qt version mismatch somewhere (qmake?) even though I set it for 5.5.1. I think my compilation of simple-player.exe is flawed.

**Comment by wardjk** [comment]
corelib/kernel/qmetatype.cpp shows QMetaType::registerNormalizedType() internal since 5.0. I don't have remnants of Qt earlier than 5.4.2 anywhere on one of the PCs I tried. Because it's an internal function, I'm not surprised it's not documented but at the same time, I am surprised simple-player.exe is trying to access it.

**Comment by wardjk** [comment]
I think this specific problem is solved. Both Qt 5.4 and 5.5 are present so having 5.5 in the path instead of 5.4 fixed it. The release build runs fine. I have a problem of a different kind only in debug mode that I'm troubleshooting now.
