### ISSUE TITLE
simple-player.exe debug error

### ISSUE THREAD

**Issue by wardjk** [vlc-qt/vlc-qt#139]
Upon directly launching the release build, no error occurs and the program seems to function normally but the debug build doesn't finish loading.
When debugging in Qt Creator, a "read access violation" occurs which triggers an exception upon executing line 28 in SimplePlayer.cpp:
`_player = new VlcMediaPlayer(_instance);`

When the release build is launched from Qt Creator, the Application Output shows:
```
Starting ...simple-player.exe...
core libvlc error: No plugins found! Check your VLC installation.
[00e6358c] core libvlc error: No plugins found! Check your VLC installation.
VLC-Qt Error: libvlc failed to load!
The program has unexpectedly finished.
```
What might cause these symptoms?

**Comment by yaung** [comment]
需要在电脑里安装vlc播放器。
you need to install vlc player before building this program,good luck

**Comment by ntadej** [comment]
Plugins need to be located in vlc/plugins subfolder relative to libvlc or set VLC_PLUGIN_PATH environment variable.

**Comment by wardjk** [comment]
**Problem Solved.**
To fix the problem, I updated Qt Creator Build Environment PATH setting to match the system PATH setting. The system PATH had been modified to include the libvlc-qt/.../bin directory after the project had been created so the two PATH settings were not synchronized. This is why the release build worked when launched directly but didn't work when launched from Qt Creator.
Your suggestion to set an environment variable prompted me to think about why Qt Creator wasn't finding libvlc upon running or debugging. Thanks for your help.
