### ISSUE TITLE
QWidget::paintEngine: Should no longer be called

### ISSUE THREAD

**Issue by camelcoding** [vlc-qt/vlc-qt#141]
With Qt5.5.1 and vlc-qt Version 1.0.1 on linux I often get the following message:

QWidget::paintEngine: Should no longer be called

I found the solution in VlcWidgetVideo::request(). 

If i remove this line: 

_video->setAttribute( Qt::WA_PaintOnScreen, true );

the message does not appear anymore. 

I dont see a performance drop. -Maybe we can get rid of this line in the future?

Best regards

**Comment by ntadej** [comment]
This seems to be Qt4 related fix/workaround. Probably it could be removed in Qt5.
