### ISSUE TITLE
missing vlc/vlc.h

### ISSUE THREAD

**Issue by dspelt** [vlc-qt/vlc-qt#142]
I'm trying to build libvlc and I get this error Error	2	error C1083: Cannot open include file: 'vlc/vlc.h': No such file or directory i am building ALL_BUILD does anybody have a idea

**Comment by ntadej** [comment]
Is LIBVLC_INCLUDE_DIR successfully set in CMake?

**Comment by dspelt** [comment]
Yes I did

**Comment by ntadej** [comment]
You need to provide more information for us to help you successfully:
 * VLC version
 * CMake version
 * Compiler and OS version (It looks like MSVC from your current input)

**Comment by dspelt** [comment]
vlc 2.2.1
cmake 3.5.1
windows 10 MSVC 2013

**Comment by ntadej** [comment]
This is an example cmake command used on AppVeyor:
```
cmake .. -G"NMake Makefiles" -DCMAKE_BUILD_TYPE=Debug -DCMAKE_INSTALL_PREFIX="c:/dev/install" -DBUILD_TESTS=ON -DLIBVLC_LIBRARY="c:/dev/dependencies/vlc/sdk/lib/libvlc.lib" -DLIBVLCCORE_LIBRARY="c:/dev/dependencies/vlc/sdk/lib/libvlccore.lib" -DLIBVLC_INCLUDE_DIR="c:/dev/dependencies/vlc/sdk/include"
```

Note that in some VLC distributions not all headers are present. I recommend using 7z zipped version as it definitely contains all required headers.

**Comment by ntadej** [comment]
This repository now includes submodule with includes so there should be no issues with them.
