### ISSUE TITLE
QWidget: Must construct a QApplication before a QWidget

### ISSUE THREAD

**Issue by soroush** [vlc-qt/vlc-qt#145]
Hi

I think an assertion check (maybe in QApplication or QWidget) fails on calling constructor of `VlcWidgetVideo` class. I'm using a promoted widget in designer (QtCreator). So the ctor is called in `setupUi()` which is generated by uic. 

Error message says:

`QWidget: Must construct a QApplication before a QWidget`

This problem is only present in debug builds.
Platform: MSVC 2015 + Qt 5.6.0

**Comment by ntadej** [comment]
Make sure you build with debug version of VLC-Qt.

**Comment by soroush** [comment]
I'm linking against `VLCQtCored` and `VLCQtWidgetsd.dll`.

**Comment by ntadej** [comment]
OK, but also when running your app, correct dlls should be found. The error you encounter is a common Qt issue that is not related to VLC-Qt.

**Comment by soroush** [comment]
I added my sysroot's bin directory to the system path. Both debug and release DLLs are accessible by application's executable.

I just wrote a minimal test application with only a `VlcWidgetVideo` on a `QMainWindow` the problem is still there.

**Comment by ntadej** [comment]
Check with [Dependency Walker](http://www.dependencywalker.com]) which DLLs are loaded. It still looks like a debug/release mismatch.

**Comment by camelcoding** [comment]
Can you show us the minimal test application?

**Comment by SlySven** [comment]
@ntadej  There is a bit of crud at the end of that [Dependency Walker](http://www.dependencywalker.com/) link - I think it is an extra "%5d" before the trailing '/' - haven't checked to see what that is in the unencoded form...!

**Comment by ntadej** [comment]
@SlySven Thanks for fixing.

**Comment by soroush** [comment]
Sorry I was busy on another project

I noticed that adding debug versions of dlls in .pro file does not cause the linker to link against actual debug dlls. 

Now that I moved release dlls somewhere else (so linker can't find them) it links against correct dlls: 

![capture1](https://cloud.githubusercontent.com/assets/920670/14769033/d682a398-0a64-11e6-86c3-4204f5ae79e0.PNG)

And it's working.
