### ISSUE TITLE
No timeChanged signal emitted when seeking using VlcWidgetSeek in pause mode

### ISSUE THREAD

**Issue by GillesDebunne** [vlc-qt/vlc-qt#146]
This problem can be reproduced using the `simple-player` example. 

Load a local video, and pause it. Now drag the position slider. As the slider moves, the video preview is updated in almost real-time.

However, the current time position label is never updated, thus still displaying the time when the video was paused, even when the mouse button is eventually released. As soon as the video is played again, everything gets back to normal.

Looking at the code, the `VlcMediaPlayer` `timeChanged` event is not fired when seeking in pause mode. This might be the underlying vlc policy since its signals are basically propagated by `VlcMediaPlayer`. Maybe be it can be mitigated by listening to other events. Anyway, this inconsistency between the slider's position and the time value displayed looks like a bug to me.

**Comment by ntadej** [comment]
Thank you for reporting this. Will fix.

**Comment by GillesDebunne** [comment]
Thanks, I confirm this fixes my issue.
