### ISSUE TITLE
[vlc_libraries_prepare.sh] Error: Output path is required (on OSX)

### ISSUE THREAD

**Issue by jbltx** [vlc-qt/vlc-qt#147]
I tried to build using the BUILDING.md file as reference.
There's no problem with dependencies using first `cmake` command. But `make prepare` gives an error:

```bash
[...]
../../../../scripts/osx/vlc_libraries_prepare.sh  /Users/jbltx/dev/vlc-qt/build/MacOSX/x64/debug
[vlc_libraries_prepare.sh] Error: Output path is required
make[3]: *** [CMakeFiles/prepare] Error 2
```

Anyone knew the same issue ?

**Comment by ntadej** [comment]
I guess VLC is not properly found. Can you check using ccmake or cmake gui what is the value of LIBVLC_BIN_DIR.

**Comment by jbltx** [comment]
There's no entry named LIBVLC_BIN_DIR:
![cmakeGUI](http://i.imgur.com/BOTSeBn.png)

**Comment by ntadej** [comment]
Your second edit may indicate a bug. Note that for static building, you link with libvlc with your final app and not with the library. What is the reason you need a static build anyway?

I will leave this open as I will include libvlc headers with the library so static building will not require any dependencies.

**Comment by ntadej** [comment]
I fixed the build and updated documentation for latest parameters. `prepare` target is still needed for tests but these dylibs are not copied with `make install` for now.
