### ISSUE TITLE
Error While installing VLCQt 

### ISSUE THREAD

**Issue by ramprasathecon** [vlc-qt/vlc-qt#149]
Hi,
I try to install VLCQt in Ubuntu 12.04. At the end of installing it is giving error.
-- Removed runtime path from "/usr/local/qml/VLCQt/libVLCQt.so.1.1.0"
-- Installing: /usr/local/qml/VLCQt/qmldir
QQmlComponent: Component is not ready
"file:///usr/local/qml/typelist.qml:2:1: plugin cannot be loaded for module "VLCQt": Cannot load library /usr/local/qml/VLCQt/libVLCQt.so.1.1.0: (libVLCQtQml.so.1.1: cannot open shared object file: No such file or directory)" 

So  I am not able to import VLCQt in my qml. Please guide me how can we resolve this.

**Comment by ntadej** [comment]
I will probably need more details:
 - You are using quite old version of VLC, there were some incompatibilities between Qt5 and VLC on this version.
 - Is there `libVLCQt.so` present in `/usr/local/qml/VLCQt/`? If yes, then just `qmltypes` generation failed which may not be "fatal". (will test this locally)
 - Are you using latest `master`?
