### ISSUE TITLE
Do not use toNativeSeparators if not to display the path

### ISSUE THREAD

**Issue by ochurlaud** [vlc-qt/vlc-qt#151]
I spotted in that you change path to native separators in several places. For instance: https://github.com/vlc-qt/vlc-qt/blob/master/src/core/Media.cpp#L73

You should not do that: as far as I know, vlc doesn't care if you use / or \\. Read this for instance: http://agateau.com/2015/qdir-separator-considered-harmful/

**Comment by ntadej** [comment]
When I last tested, there were some issues on Windows with paths and VLC. Will test again if this is not the case anymore.

**Comment by ntadej** [comment]
Tested on Windows. Tests crash when I remove native separators when passing `F:/VLC-Qt/vlc-qt/tests/samples/sample.mp3` to new VlcMedia.

If you know a way to overcome this issue, feel free to open a PR.
