### ISSUE TITLE
vlc_common.h when running make

### ISSUE THREAD

**Issue by azcoppen** [vlc-qt/vlc-qt#152]
Building on OS X (Capitan), following instructions. All fine until hitting make -j8:

/Users/None/vlc-qt/vlc-qt-master/src/core/Audio.cpp:30:10: fatal error: 'vlc_common.h' file not found
#include <vlc_common.h>

make[1]: *** [src/core/CMakeFiles/Core.dir/all] Error 2
make: *** [all] Error 2

**Comment by ntadej** [comment]
In latest master you need to init git submodules. Will add to instructions.

**Comment by azcoppen** [comment]
Thanks! Got it running successfully (temp hack) by adding libvlc files to the src folder, to which it built successfully. All went very nicely into /usr/local/lib/VLCQtCore.framework (etc). A little expansion on the instructions needed before running cmake would be really great.

**Comment by ntadej** [comment]
The comment for submodule is already present in root README.md and also when generating docs. Will add a note also to BUILDING.md to avoid problems
