### ISSUE TITLE
Issue with Building on Windows

### ISSUE THREAD

**Issue by joshmarshall1995** [vlc-qt/vlc-qt#156]
After downloading the new source code I am unable to build the library for windows. I point to directory in CMAKE, set the dependencies for Qt (I am using 5.5.1), CMAKE generates the BUILD and INSTALL files - then when I attempt to build the file it reads the error : Error	23	error LNK1181: cannot open input file '..\..\core\VLCQtCore.lib'	C:\VLCNEW\vlc-qt-master\src\plugins\VLCQt\LINK	PluginQml

Do you have any suggestions on how to solve this or could you possibly put up a pre-built release for the source code that contains the ability to process frames by subclassing VideoFrame.

**Comment by ntadej** [comment]
Prebuilt versions are available on AppVeyor. Just use the latest master build.

**Comment by joshmarshall1995** [comment]
Could you point me to the build?

**Comment by ntadej** [comment]
Note that this is a Qt 5.6 build, which is recommended as it is LTS version.
https://ci.appveyor.com/project/ntadej/vlc-qt/build/1.1.0.179

**Comment by joshmarshall1995** [comment]
Thankyou got that running, this is a separate issue but could you give a small example on how to run a feed and use the videoframe/abstractvideoframe to get the data.
