### ISSUE TITLE
vlc-qt 1.1.0 MSVC2015 Build failed

### ISSUE THREAD

**Issue by spartucus** [vlc-qt/vlc-qt#161]
The VLC-Qt 1.0.1 Release works fine, but I need debug version of vlc-qt. So I build on my own, here's env:
- Win7 x64
- Qt-5.6.1-msvc2015
- Visual Studio 2015
- VLC-2.2.4
- vlc-qt 1.1.0 (the lastest version on github)

After cmake, I open generated sln by VS2015, but when I build the sln, It fails with errors 

> "ERROR LNK2019    Unresolved external symbol _libvlc_video_set_callbacks，the symbol referenced by  "public: void __thiscall VlcAbstractVideoStream::setCallbacks(class VlcMediaPlayer *)" (?setCallbacks@VlcAbstractVideoStream@@QAEXPAVVlcMediaPlayer@@@Z) Core    D:\SDKs\vlc-qt\build\src\core\AbstractVideoStream.obj   1"

Apparently, there is something wrong with vlc lib. which version of vlc should I use, or Is my solution of build right? Any advice would be appreciated.

**Comment by ntadej** [comment]
There are two scripts in win folder to re-generate libvlc lib for linking with MSVC. I still have to integrate those into main build scripts.

Otherwise, I will (finally) publish binaries for 1.1.0. As 1.0.1 they contain debug build.

**Comment by Szpaqn** [comment]
It is worth noticing, that I could not run my Application in debug mode using MSVC2015 until I installed VisualStudio 2013.
I'm not an expert, but it seems, that you need some debug 'stuff' from VisualStudio 2013.
