### ISSUE TITLE
qml library files are installed in the wrong directory

### ISSUE THREAD

**Issue by martinkg** [vlc-qt/vlc-qt#162]
Hi,

with the recent version vlc-qt-1.1.0 the qml libraries will be installed on Fedora 24 to the following folder:
/usr/qml/VLCQt/libVLCQt.so
/usr/qml/VLCQt/libVLCQt.so.1.1
/usr/qml/VLCQt/libVLCQt.so.1.1.0
/usr/qml/VLCQt/qmldir

but this shoult be:
/usr/lib64/qml/VLCQt/libVLCQt.so
/usr/lib64/qml/VLCQt/libVLCQt.so.1.1
/usr/lib64/qml/VLCQt/libVLCQt.so.1.1.0
/usr/lib64/qml/VLCQt/qmldir

the attached patch corrects this.
[vlc-qt-1.1.0-CMakeLists.patch.txt](https://github.com/vlc-qt/vlc-qt/files/357028/vlc-qt-1.1.0-CMakeLists.patch.txt)

**Comment by ntadej** [comment]
Thank you for this patch. It seems that qml path is system dependend. Will check on all platforms.

**Comment by ntadej** [comment]
@martinkg Also, you can try this in `feature/gnuinstalldirs` branch. Add cmake flag `-DSYSTEM_QML=ON`

**Comment by martinkg** [comment]
Hi ntadej,

the %cmake macro on Fedora set the following variables:

rpm -E "%cmake"

  CFLAGS="${CFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic}" ; export CFLAGS ; 
  CXXFLAGS="${CXXFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic}" ; export CXXFLAGS ; 
  FFLAGS="${FFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules}" ; export FFLAGS ; 
  FCFLAGS="${FCFLAGS:--O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -m64 -mtune=generic -I/usr/lib64/gfortran/modules}" ; export FCFLAGS ; 
  LDFLAGS="${LDFLAGS:--Wl,-z,relro -specs=/usr/lib/rpm/redhat/redhat-hardened-ld}" ; export LDFLAGS ; 
  /usr/bin/cmake \
        -DCMAKE_C_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_CXX_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_Fortran_FLAGS_RELEASE:STRING="-DNDEBUG" \
        -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON \
        -DCMAKE_INSTALL_PREFIX:PATH=/usr \
        -DINCLUDE_INSTALL_DIR:PATH=/usr/include \
        -DLIB_INSTALL_DIR:PATH=/usr/lib64 \
        -DSYSCONF_INSTALL_DIR:PATH=/etc \
        -DSHARE_INSTALL_PREFIX:PATH=/usr/share \
%if "lib64" == "lib64" 
        -DLIB_SUFFIX=64 \
%endif 
        -DBUILD_SHARED_LIBS:BOOL=ON

you uses CMAKE_INSTALL_PREFIX and not CMAKE_INSTALL_LIBDIR, i patched this in Dependencies.cmake

diff -Naur config/Dependencies.cmake.orig config/Dependencies.cmake
--- config/Dependencies.cmake.orig	2016-08-14 21:29:13.990185529 +0200
+++ config/Dependencies.cmake	2016-08-14 21:30:47.500343673 +0200
@@ -80,6 +80,6 @@
             OUTPUT_VARIABLE QT_INSTALL_QML OUTPUT_STRIP_TRAILING_WHITESPACE
         )
     ELSE()
-        SET(QT_INSTALL_QML ${CMAKE_INSTALL_PREFIX}/qml)
+        SET(QT_INSTALL_QML ${CMAKE_INSTALL_LIBDIR}/qml)
     ENDIF()
 ENDIF()

maybe you can change this in your code ? otherwise i must set -DCMAKE_INSTALL_PREFIX:PATH=%{_libdir} and this is really not correct.

**Comment by ntadej** [comment]
If you use `-DSYSTEM_QML=ON` cmake should ask qmake where to install QML files so no need to patch. I will make gnuinstalldirs optional as they seem not to work on rpm based distros.

I will let you know, when I have a new version to test.

**Comment by martinkg** [comment]
test with las git version 5cdcadbdce66fe2631598c967f8a659d08b9dec7

cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON . -DBUILD_TESTS:BOOL=ON -DSYSTEM_QML:BOOL=OFF

only compiles fine with this patch:

--- config/Dependencies.cmake.orig	2016-08-14 21:29:13.990185529 +0200
+++ config/Dependencies.cmake	2016-08-14 21:30:47.500343673 +0200
@@ -80,6 +80,6 @@
             OUTPUT_VARIABLE QT_INSTALL_QML OUTPUT_STRIP_TRAILING_WHITESPACE
         )
     ELSE()
-        SET(QT_INSTALL_QML ${CMAKE_INSTALL_PREFIX}/qml)
+        SET(QT_INSTALL_QML ${CMAKE_INSTALL_LIBDIR}/qml)
     ENDIF()
 ENDIF()

otherwise, the libraries  libVLCQt.so* are installed to /usr/lib and not to /usr/lib64

not correct:
-- Installing: /home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.1git5cdcadb.fc24.x86_64/usr/qml/VLCQt/libVLCQt.so.1.1.0
-- Installing: /home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.1git5cdcadb.fc24.x86_64/usr/qml/VLCQt/libVLCQt.so.1.1
-- Installing: /home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.1git5cdcadb.fc24.x86_64/usr/qml/VLCQt/libVLCQt.so

**Comment by ntadej** [comment]
You need to set SYSTEM_QML ON not OFF!

**Comment by martinkg** [comment]
I used this command to build:

cmake -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON . -DBUILD_TESTS:BOOL=ON -DSYSTEM_QML:BOOL=ON

this is the result:
-- Installing: /home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.1git5cdcadb.fc24.x86_64/VLCQt/libVLCQt.so.1.1.0
-- Installing: /home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.1git5cdcadb.fc24.x86_64/VLCQt/libVLCQt.so.1.1
-- Installing: /home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.1git5cdcadb.fc24.x86_64/VLCQt/libVLCQt.so
-- Set runtime path of "/home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.1git5cdcadb.fc24.x86_64/VLCQt/libVLCQt.so.1.1.0" to ""
-- Installing: /home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.1git5cdcadb.fc24.x86_64/VLCQt/qmldir
CMake Error at src/plugins/VLCQt/cmake_install.cmake:92 (EXECUTE_PROCESS):
  execute_process called with no value for WORKING_DIRECTORY.
Call Stack (most recent call first):
  src/cmake_install.cmake:40 (include)
  cmake_install.cmake:122 (include)
  
Makefile:74: recipe for target 'install' failed
make: *** [install] Error 1

If i use this patch all is fine:
`--- config/Dependencies.cmake.orig	2016-08-14 21:29:13.990185529 +0200
+++ config/Dependencies.cmake	2016-08-14 21:30:47.500343673 +0200
@@ -80,6 +80,6 @@
             OUTPUT_VARIABLE QT_INSTALL_QML OUTPUT_STRIP_TRAILING_WHITESPACE
         )
     ELSE()
-        SET(QT_INSTALL_QML ${CMAKE_INSTALL_PREFIX}/qml)
+        SET(QT_INSTALL_QML ${CMAKE_INSTALL_LIBDIR}/qml)
     ENDIF()
 ENDIF()`

**Comment by martinkg** [comment]
sorry don't no how to post a patch here
i replaced in config/Dependencies.cmake the line 
      SET(QT_INSTALL_QML ${CMAKE_INSTALL_PREFIX}/qml)
by
      SET(QT_INSTALL_QML ${CMAKE_INSTALL_LIBDIR}/qml)

and all is fine.

**Comment by ntadej** [comment]
I will setup a virtual machine to test this so I will not bother you anymore, but I'm busy at the moment, so give me a week.

**Comment by martinkg** [comment]
Sorry did not work with your mentioned changes in rpm spec file with last git ff15c34:

+ cp -pr LICENSE.md /home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.2gitff15c34.fc24.x86_64/usr/share/licenses/vlc-qt
+ exit 0

RPM build errors:
    File not found: /home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.2gitff15c34.fc24.x86_64/usr/lib64/qt5/qml/VLCQt/libVLCQt.so
    File not found: /home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.2gitff15c34.fc24.x86_64/usr/lib64/qt5/qml/VLCQt/libVLCQt.so.1.1
    File not found: /home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.2gitff15c34.fc24.x86_64/usr/lib64/qt5/qml/VLCQt/libVLCQt.so.1.1.0
    File not found: /home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.2gitff15c34.fc24.x86_64/usr/lib64/qt5/qml/VLCQt/qmldir
    Directory not found: /home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.2gitff15c34.fc24.x86_64/usr/lib64/qt5/qml/VLCQt

[martin@fc24 SPECS]$ find /home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.2gitff15c34.fc24.x86_64/ -name libVLCQt.so.1.1 -print

/home/martin/rpmbuild/BUILDROOT/vlc-qt-1.1.0-0.2gitff15c34.fc24.x86_64/usr/qml/VLCQt/libVLCQt.so.1.1

could you please give me access to your rpm spec file ?
Thanks.

**Comment by ntadej** [comment]
https://gist.github.com/ntadej/d233c694ec4ed6344c13cff384eac552

**Comment by martinkg** [comment]
works now, thanks.

**Comment by ntadej** [comment]
OK, I will release this in 1.1.1 soon as I test it on Ubuntu and Windows.
