### ISSUE TITLE
Error build last vlc-qt

### ISSUE THREAD

**Issue by thefastman** [vlc-qt/vlc-qt#170]
Try to build last cloned vlc-qt

d$ cmake .. -DCMAKE_BUILD_TYPE=Release  -DLIBVLC_LIBRARY=/usr/lib/libvlc.so -DLIBVLCCORE_LIBRARY=/usr/lib/libvlccore.so.7
-- Building VLC-Qt 1.1.0
-- Git revision: cadc9e2
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Build statically: OFF
-- Using Qt 5.7.0
-- Found LibVLC include-dir path: /usr/include
-- Found LibVLC library path:/usr/lib/libvlc.so
-- Found LibVLCcore library path:/usr/lib/libvlccore.so.7
-- Configuring done
-- Generating done

then make:

../../src/core/libVLCQtCore.so.1.1.0: undefined reference to `libvlc_audio_equalizer_get_amp_at_index'
../../src/core/libVLCQtCore.so.1.1.0: undefined reference to `libvlc_media_player_set_equalizer'
../../src/core/libVLCQtCore.so.1.1.0: undefined reference to `libvlc_audio_equalizer_get_preset_count'
../../src/core/libVLCQtCore.so.1.1.0: undefined reference to `libvlc_audio_equalizer_set_preamp'
../../src/core/libVLCQtCore.so.1.1.0: undefined reference to `libvlc_audio_equalizer_get_band_frequency'
../../src/core/libVLCQtCore.so.1.1.0: undefined reference to `libvlc_audio_equalizer_get_band_count'
../../src/core/libVLCQtCore.so.1.1.0: undefined reference to `libvlc_audio_equalizer_get_preset_name'
../../src/core/libVLCQtCore.so.1.1.0: undefined reference to `libvlc_audio_equalizer_new_from_preset'
../../src/core/libVLCQtCore.so.1.1.0: undefined reference to `libvlc_audio_equalizer_new'
../../src/core/libVLCQtCore.so.1.1.0: undefined reference to `libvlc_audio_equalizer_get_preamp'
../../src/core/libVLCQtCore.so.1.1.0: undefined reference to `libvlc_audio_equalizer_release'
../../src/core/libVLCQtCore.so.1.1.0: undefined reference to `libvlc_audio_equalizer_set_amp_at_index'
collect2: error: ld returned 1 exit status

$ cvlc -v
VLC media player 2.1.6 Rincewind (revision 2.1.6-0-gea01d28)

How I can solve it ?

**Comment by ntadej** [comment]
See `BUILDING.md`. You need to specify VLC version if you do not use the latest one.
