### ISSUE TITLE
Failed to build under Windows

### ISSUE THREAD

**Issue by Umriyaev** [vlc-qt/vlc-qt#171]
I'm trying to build vlc-qt under Windows 7 64bit using ninja, cmake v3.6.2, mingw-w64 4.3.0
I have Qt 5.7
I installed vlc, but apparently Windows installer doesn't come with sdk. So I downloaded 7z archive vlc-2.2.4-win64 and extracted it. 
I used build code from [How to build](https://github.com/vlc-qt/vlc-qt/blob/master/BUILDING.md), but changed it to the following:

```
$ md build
$ cd build
$ cmake .. -GNinja -DCMAKE_BUILD_TYPE=Debug ^
-DCMAKE_INSTALL_PREFIX="c:/install/vlc-qt/msvc64" ^
 -DLIBVLC_LIBRARY="c:/Program Files/VideoLAN/vlc-2.2.4-win64/vlc-2.2.4/sdk/lib/libvlc.lib" ^ 
-DLIBVLCCORE_LIBRARY="c:/Program Files/VideoLAN/vlc-2.2.4-win64/vlc-2.2.4/sdk/lib/libvlccore.lib" ^ 
-DLIBVLC_INCLUDE_DIR="c:/Program Files/VideoLAN/vlc-2.2.4-win64/vlc-2.2.4/sdk/include"
$ ninja
$ ninja install
```

After running ninja I'm getting following logs. It's failing on the [11/73] step:
[vlc-qt-ninja-log.txt](https://github.com/vlc-qt/vlc-qt/files/479515/vlc-qt-ninja-log.txt)

What might be causing the problem?

**Comment by ntadej** [comment]
There are some issues with linking with Qt. Did you build Qt on your own?

**Comment by Umriyaev** [comment]
Nope, I downloaded online installer for Windows

**Comment by mastash3ff** [comment]
Ran across this same issue trying to get Qt Creator in Windows to compile "simple-player" from the prebuilt vlc-qt libraries at https://vlc-qt.tano.si/

**Comment by ntadej** [comment]
You are mixing MSVC and MinGW based Qt builds. This is not supported.
