### ISSUE TITLE
Cant see VlcWidgetVideo

### ISSUE THREAD

**Issue by mardzo** [vlc-qt/vlc-qt#175]
hello
this is a slot i activate via qpushbutton:

void OPQWidgetOverload::openVideo()
{

    QDialog *holder = new QDialog(this);
    holder->resize(600,300);

    QString url = "rtsp://admin:admin@192.168.1.110:554/cam/realmonitor?channel=1subtype=1";

    VlcWidgetVideo *video = new VlcWidgetVideo(holder);

    VlcInstance *_instance = new VlcInstance(VlcCommon::args(), this);
    VlcMediaPlayer *_player = new VlcMediaPlayer(_instance);
    _player->setVideoWidget(video);

    holder->show();

      VlcMedia *_media = new VlcMedia(url, _instance);
     _player->open(_media);
}

When i press the button that activates this slot i see the QDialog but the VlcWidgetVideo is not there and i cant see the stream ;(. Funny thing is if i dont set a VlcVideoWidget to _player, the direct3D stream is outputed in another window and i can see the video stream so i know that it exists. I cant figure out why i cant see the VlcWidgetVideo widget.

Does anyone know a fix about this problem?
Thanks in advance

**Comment by ntadej** [comment]
You need to add the widget to the QDialog. Currently holder acts just as a parent. You still need to add video widget to a layout explicitly.

**Comment by mardzo** [comment]
You are right. Thanks for your answer.
