### ISSUE TITLE
CMake Error at cmake/FindLIBVLC.cmake:99 (MESSAGE):

### ISSUE THREAD

**Issue by stackprogramer** [vlc-qt/vlc-qt#186]
i installed libvlc from apt-get install libvlc-dev but for making your project it returns this errors in Debian os. any idea?
thank in advance

> root@debian:/home/sp/Documents/vlc-qt-master/build# cmake ..
> -- Building VLC-Qt 1.1.0
> fatal: Not a git repository (or any of the parent directories): .git
> -- Build statically: OFF
> -- Using Qt 5.7.0
> -- Installing to system QML import path: OFF
> CMake Error at cmake/FindLIBVLC.cmake:99 (MESSAGE):
>   Could not find LibVLC
> Call Stack (most recent call first):
>   config/Dependencies.cmake:59 (FIND_PACKAGE)
>   CMakeLists.txt:50 (INCLUDE)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/sp/Documents/vlc-qt-master/build/CMakeFiles/CMakeOutput.log".
> root@debian:/home/sp/Documents/vlc-qt-master/build#  cmake .. -DCMAKE_BUILD_TYPE=Debug
> -- Building VLC-Qt 1.1.0
> fatal: Not a git repository (or any of the parent directories): .git
> -- Build statically: OFF
> -- Using Qt 5.7.0
> -- Installing to system QML import path: OFF
> CMake Error at cmake/FindLIBVLC.cmake:99 (MESSAGE):
>   Could not find LibVLC
> Call Stack (most recent call first):
>   config/Dependencies.cmake:59 (FIND_PACKAGE)
>   CMakeLists.txt:50 (INCLUDE)
> 
> 
> -- Configuring incomplete, errors occurred!
> See also "/home/sp/Documents/vlc-qt-master/build/CMakeFiles/CMakeOutput.log".
> root@debian:/home/sp/Documents/vlc-qt-master/build#

**Comment by DrageFabeldyr** [comment]
The same problem for Windows

**Comment by ntadej** [comment]
libvlccore-dev is also required

For windows, you need to download .7z packages as installers might not include full SDK (similarly on macOS).

**Comment by DrageFabeldyr** [comment]
do you mean these .7z packages https://github.com/vlc-qt/vlc-qt/releases ?
as i understand it's compiled libraries for including in project or i've mistaken

**Comment by ntadej** [comment]
No, as i understood you want to build VLC-Qt. Then you also need VLC SDK.

**Comment by DrageFabeldyr** [comment]
Yes, that's what i want. So SDK i need could be taken from here - http://download.videolan.org/pub/videolan/vlc/2.2.4/win64/ am i right?

**Comment by ntadej** [comment]
Yes. This could also be used to add missing headers on macOS.

**Comment by DrageFabeldyr** [comment]
Yea. I've already tried and succeeded. i've tried SDK from _win64_ and _win32_. With _win64_ i have some problems with _make_ but with _win32_ it's ok may be it's because i use _mingw32_. Finally i have compiled library and added it in simple-player-example to check. It works absolutely the same with what you can download [here](https://vlc-qt.tano.si/) - fine for release and crashes when you try to debug.
Debug crashes in line 83 of ui_SimplePlayer.h
`video = new VlcWidgetVideo(centralwidget);`
There are also debug versions of library dlls but they work the same way.

I understand that it's another question but is there a way to have working debug version?

**Comment by ntadej** [comment]
Please make sure that you use debug VLC-Qt, debug Qt and debug build of your app the same time!

**Comment by DrageFabeldyr** [comment]
It seems i've succeeded. I made two CMake configurations - Debug and Release in two folders (cmake_install_prefix) - VLC and VLCd. Then put them both to simple-player-example folder. And copied everything from VLC/bin to simple-player/release and from VLCd/bin to simple-player/debug. Then added:
`unix:!macx|win32: LIBS += -L$$PWD/VLC/lib/ -llibVLCQtCore.dll
unix:!macx|win32: LIBS += -L$$PWD/VLC/lib/ -llibVLCQtWidgets.dll

INCLUDEPATH += $$PWD/VLC/include
DEPENDPATH += $$PWD/VLC/include`
in .pro file for Release

and to run in Debug just change first two strings to
`unix:!macx|win32: LIBS += -L$$PWD/VLCd/lib/ -llibVLCQtCored.dll
unix:!macx|win32: LIBS += -L$$PWD/VLCd/lib/ -llibVLCQtWidgetsd.dll`
then rebuild all and run

may be it's too complicated but it works. Thanx.

**Comment by hepeng7259** [comment]
> libvlccore-dev 也是必需的
> 
> 对于 Windows，您需要下载 .7z 包，因为安装程序可能不包含完整的 SDK（macOS 类似）。

sudo apt-get install libvlccore-dev   成功解决问题，感谢
