### ISSUE TITLE
VLC-Qt 0.9.0 Dependency Issues

### ISSUE THREAD

**Issue by mualloc** [vlc-qt/vlc-qt#190]
Hello,
I am using VLC-Qt 0.9.0 with MSVC 2008 in QtCreator. When I was building in debug mode, there were no problems. However, when I switched to release mode, problems occurred. After that, I opened vlc-qt-widgets.dll with dependency walker and I realized that vlc-qt-widgets.dll depends on QTGUID4.dll and QTCORED4.dll, however; since I want to build in release mode this causes run time error when I want to create for example a demo player alike widget. The error message is:

qwidget: must construct a qapplication before a qpaintdevice

So, my question is is there a way to use vlc-qt 0.9.0 in release mode smoothly?

**Comment by ntadej** [comment]
Build VLC-Qt in debug mode to use with debug apps and build in release mode to use with release apps. This was already discussed several times.

I would also recommend migrating to 1.1.
