### ISSUE TITLE
QWidget: Must construct a QApplication before a QWidget

### ISSUE THREAD

**Issue by ShettyRa** [vlc-qt/vlc-qt#197]
Hi,

I've installed the vlc-qt librarys and build the simple-player example, by using _MSVC2013_64bit-Debug.
When I try running it, I get the following error(application output):

```
> Starting C:\Users\rshe\Downloads\examples-master\examples-master\build-simple-player-Desktop_Qt_5_6_2_MSVC2013_64bit-Debug\src\src\debug\simple-player.exe...
> **QWidget: Must construct a QApplication before a QWidget**
> C:\Users\rshe\Downloads\examples-master\examples-master\build-simple-player-Desktop_Qt_5_6_2_MSVC2013_64bit-Debug\src\src\debug\simple-player.exe exited with code 1
```

Compile Output:
```
13:04:58: Running steps for project simple-player...
13:04:58: Configuration unchanged, skipping qmake step.
13:04:59: Starting: "C:\Qt\Qt5.6.2\Tools\QtCreator\bin\jom.exe" 
	cd src\ && ( if not exist Makefile C:\Qt\Qt5.6.2\5.6\msvc2013_64\bin\qmake.exe C:\Qt\libvlc-qt\src\examples\simple-player\src\src.pro -spec win32-msvc2013 "CONFIG+=debug" "CONFIG+=qml_debug" -o Makefile ) && C:\Qt\Qt5.6.2\Tools\QtCreator\bin\jom.exe -f Makefile
	C:\Qt\Qt5.6.2\Tools\QtCreator\bin\jom.exe -f Makefile.Debug
13:04:59: The process "C:\Qt\Qt5.6.2\Tools\QtCreator\bin\jom.exe" exited normally.
13:04:59: Elapsed time: 00:01.

```
I am running the app on  Qt creator 5.6.2
I have also added path of all the vlc lib, msvc2013_64/bin to environment variables  
I have also  provided proper link to the libs
src.pro:
```
TARGET      = simple-player
TEMPLATE    = app
CONFIG 	   += c++11

QT         += widgets

SOURCES    += main.cpp \
    SimplePlayer.cpp \
    EqualizerDialog.cpp

HEADERS    += SimplePlayer.h \
    EqualizerDialog.h

FORMS      += SimplePlayer.ui \
    EqualizerDialog.ui

INCLUDEPATH += C:\\Qt\\libvlc-qt\\include

LIBS     += -LC:\\Qt\\libvlc-qt\\lib \
        -lVLCQtCore.lib \
        -lVLCQtWidgets.lib
```
Any hint on what I'm doing wrong?

**Comment by ntadej** [comment]
First, you should tell, which version of VLC-Qt you use and if you built it by yourself.

Are you linking with debug version of VLC-Qt? From the look of the `src.pro` it doesn't seem like it. You should use the `lib` files with the suffix `d`.

**Comment by ShettyRa** [comment]
Thanks for the quick reply
 I'm using VLC-Qt_1.1.0_win64 from [https://github.com/vlc-qt/vlc-qt/releases](url)
Yes I build it by myself 
I am linking it with the VLC-Qt_1.1.0_win64 (i renamed it to libvlc-qt)
I have tried with the suffix  d 
```
LIBS     += -LC:\\Qt\\libvlc-qt\\lib \
        -lVLCQtCore.d \
        -lVLCQtWidgets.d
```
but same error

**Comment by ntadej** [comment]
You need to link with `VLCQtCored.lib`.

**Comment by ShettyRa** [comment]
i have also added VLCQtCored.lib still same error 
`LIBS     += -LC:\\Qt\\libvlc-qt\\lib \
        -lVLCQtCore.lib.d \
        -lVLCQtCored.lib.d \
        -lVLCQtWidgets.lib.d`

**Comment by ntadej** [comment]
`VLCQtCored.lib` != `VLCQtCore.lib.d`

Anyhow, you always need to use the same configuration for VLC-Qt and your app. Make sure you have built VLC-Qt also with debug mode.

This has been discussed a lot here and is also documented.

**Comment by ShettyRa** [comment]
VLCQtCored.lib = VLCQtCored.d ?

As suggested I made the changes but still same error 

I have seen the discussion and tried to make the changes but it didn't work. 
where can I find the documentation? 
Is it the problem of my compiler MSVC2013_64bit?

**Comment by ntadej** [comment]
There are no specific instructions as filenames vary between different compiler versions (and if you build by yourself). I suggest you make a clean debug build of VLC-Qt with the same compiler and then try again.

Also, is there a reason not to use the latest compiler?

**Comment by ShettyRa** [comment]
I'm trying to run simple-player, now I downloaded **VLC-Qt_1.0.1_win64_msvc2013** as my compiler is MSVC2013_64bit. 
Same problem compile sucessfully but no GUI i get  QWidget: Must construct a QApplication before a QWidget
I have provided proper link and i'm using debug build config. 
`LIBS       += -L"C:\Users\rshe\Desktop\Qt projects\VLC-Qt_1.0.1_win64_msvc2013\lib" -lVLCQtCored -lVLCQtWidgetsd

INCLUDEPATH += "C:\Users\rshe\Desktop\Qt projects\VLC-Qt_1.0.1_win64_msvc2013\include"`

**Comment by ShettyRa** [comment]
Also, is there a reason not to use the latest compiler?
Not really

**Comment by ShettyRa** [comment]
It's working with the Release configuration but not with the debug any idea what might be the problem? 
I am trying to stream a video from camera stream appears but with a high latency. what leads to this high latency any idea?

thank you
