### ISSUE TITLE
How to reduce latency ?

### ISSUE THREAD

**Issue by ShettyRa** [vlc-qt/vlc-qt#198]
I am streaming a live video streaming with simple-player(vlc-qt) but I encounter a huge latency. 
can anyone suggest what I need to do in order to kill this latency?   

As much as Iknow this latency is caused due to buffering (caching time). 

So my question is how can I reduce this buffering time for example: 
`player->setBufferValue(1); //playback goes on  if 1 packet buffered, i.e. immediatly`

Which part of the app deals with the latency?

Thank you

**Comment by jpiat** [comment]
did you find a solution to this issue ? I have tried the following :
```
        QStringList` option_list;
        option_list.append(":network-caching=100");
        option_list.append(":clock-jitter=0");
        option_list.append(":clock-synchro=0");

        _media = new VlcMedia(stream_address, false, _instance);
        _media->setOptions(option_list);
        _player->open(_media);
```

but i still have a very large delay.
