### ISSUE TITLE
Is there a way to adjust the buffer setting (example : set to 50ms ). For live video streaming?

### ISSUE THREAD

**Issue by ShettyRa** [vlc-qt/vlc-qt#200]
Hi all,
I am currently playing around with a network camera and am getting the rtsp video stream using VLC-QT on Qt Creator, however, the streaming buffer is so large there is ~ 2-3 second delay.

Is there a way to adjust the buffer setting (example : set to 50ms ). For live video streaming

Anybody run into this and try to change the buffer setting?  On Windows Qt Creator

**Comment by liuxuan5220** [comment]
Hello, i have encountered the same problem .That you have solved？

**Comment by ShettyRa** [comment]
Yes, you have to pass the string ":network-caching=100" to the vlcmedia. 

works fine with QWidgets but I am still struck with the qml i couldn't pass the string network-caching.

**Comment by liuxuan5220** [comment]
Thank you for the way. I will continue to look for qml in the solution.

**Comment by Talkless** [comment]
Could this be reopened for QML ? I just got same issue, default caching provides is way too big delay.

**Comment by gregorsimoncic** [comment]
@ShettyRa > Yes, you have to pass the string ":network-caching=100" to the vlcmedia. works fine with QWidgets but I am still struck with the qml i couldn't pass the string network-caching.

Could you please paste your solution here? Thanks. I am also using QWdigets, but seems it doesn't accept my arguments...
