### ISSUE TITLE
core vout display error: Failed to set on top     libvlc: Failed to set on top

### ISSUE THREAD

**Issue by ShettyRa** [vlc-qt/vlc-qt#201]
Hi all, 

I am trying to stream video from my cam on vlc player using URL 
this is my url 
rtsp://admin:admin@192.168.253.99:554/cam/realmonitor?channel=1&subtype=0&unicast=true
I get the stream bet I get errors 
```
core input error: ES_OUT_RESET_PCR called
libvlc: ES_OUT_RESET_PCR called
core input error: ES_OUT_RESET_PCR called
libvlc: ES_OUT_RESET_PCR called
core decoder error: Could not convert timestamp 0
libvlc: Could not convert timestamp 0 
```
in order to reduce the caching to get live video without delay, i added :network-caching=100 at the end of the url bet there is no change, there is still a long delay

rtsp://admin:admin@192.168.253.99:554/cam/realmonitor?channel=1&subtype=0&unicast=true :network-caching=100

Errors:

```
core input error: ES_OUT_RESET_PCR called
libvlc: ES_OUT_RESET_PCR called
core input error: ES_OUT_RESET_PCR called
libvlc: ES_OUT_RESET_PCR called
core decoder error: Could not convert timestamp 0
libvlc: Could not convert timestamp 0
```
any idea how to add **network-caching**

**Comment by ShettyRa** [comment]
After some searching, I found that network-caching option is present is 

> libvlccore.dll

 file.  
and all the above-mentioned errors are also present in the libvlccore.dll file. 
I was wondering how can I call the option network-caching from Qt I tried by adding :network-caching=100 to my URL, as mentioned above, it doesn't work. 

Looking for some help 

Thanks

**Comment by ntadej** [comment]
`setOption` on `VlcMedia` instance is for adding media based options. You should use the full syntax for example `media->setOption(":network-caching=100")`.

**Comment by ShettyRa** [comment]
Thanks a lot
