### ISSUE TITLE
Fullscreen video?

### ISSUE THREAD

**Issue by anantkamath** [vlc-qt/vlc-qt#21]
Is there a way to toggle fullscreen for the video player? 
I tried libvlc_toggle_fullscreen(_vlcMediaPlayer); , but that didn't work (the code built, but not change when the fullscreen button was clicked), is it because it is 'embedded' in a  Qt widget?
If so, what other way is there to display the video in fullscreen?

Thanks

**Comment by ntadej** [comment]
This should be implemented in the application. Closing.
