### ISSUE TITLE
cannot build vlc-qt for my mac

### ISSUE THREAD

**Issue by islamouahouda** [vlc-qt/vlc-qt#238]
Hello,

I am trying to build vlc-qt
in my mac but i cannot do it due to this problem 
my vlc is in /applications

this is my error : 
CMake Error: The source directory "/Users/adamlaarif/Downloads/VLC-Qt_1.1.0_macos" does not appear to contain CMakeLists.txt.

**Comment by ntadej** [comment]
You downloaded the pre-built archive. Please, download the source to be able to build it.

**Comment by islamouahouda** [comment]
how to use the pre-builted one ? in a Qt code?
