### ISSUE TITLE
Enabling DXVA causes Rincewind to fail to display video on QMLVideoObject

### ISSUE THREAD

**Issue by VileLasagna** [vlc-qt/vlc-qt#27]
Pretty much as in the description. 

Using the Libavcodec plugins from Rincewind (2.1.1) and vlc-qt 0.10.0 compiled with QML (herpderp) for QT 5.1.1 VC12 x86. 

Eveything works fine until --avcodec-hw=dxva2.lo is passed to the underlying VLCInstance on creation. 
I get

main vout display error: Failed to change zoom
main vout display error: Failed to set on top
main vout display error: Failed to change source AR

from VLC's console output and video fails to display. 
Tested using the widget example, it displays "failed to set on top" but actually seems to work fine.

Thought it could be some sort of memory access issue with DX versioning issues and actually recompiled QT forcing Angle to use D3D11. Problem remained.

**Comment by ntadej** [comment]
Can you please test with the latest version?

**Comment by ntadej** [comment]
Feel free to let me know, if you still experience this issue.
