### ISSUE TITLE
Building VLC-Qt for mingw-64 windows problem

### ISSUE THREAD

**Issue by levius0** [vlc-qt/vlc-qt#270]
Hello,  i am trying to build VLC-Qt for mingw-x64  using Ninja but get unexpected errors. Maybe you know why they appeared.
First is the build
![image](https://user-images.githubusercontent.com/20255584/99365816-d3fbd900-28c8-11eb-804b-5db6ee21dda7.png)
and after that as i undestand i need to run ninja but i get errors
![image](https://user-images.githubusercontent.com/20255584/99365909-efff7a80-28c8-11eb-9bc0-f53f37e8e868.png)
![image](https://user-images.githubusercontent.com/20255584/99365929-f68df200-28c8-11eb-8e42-5ae47bdb4557.png)
![image](https://user-images.githubusercontent.com/20255584/99365954-fd1c6980-28c8-11eb-8a07-0d30ef01ba19.png)
I am new in building libs from sources maybe you can give an advise.

**Comment by levius0** [comment]
After troubles with ninja I'v tryed to do it with mingw makefiles as in this issue https://github.com/vlc-qt/vlc-qt/issues/263 but still getting an error. 
![image](https://user-images.githubusercontent.com/20255584/99366508-c561f180-28c9-11eb-9ca0-9c368bf49392.png)
![image](https://user-images.githubusercontent.com/20255584/99366530-cc88ff80-28c9-11eb-8127-0e248a2f36b6.png)
![image](https://user-images.githubusercontent.com/20255584/99366546-d1e64a00-28c9-11eb-9951-362041713aa2.png)
![image](https://user-images.githubusercontent.com/20255584/99366570-d7439480-28c9-11eb-82fc-10d8ef14cbac.png)

**Comment by levius0** [comment]
From this example i don't understant how you specifie the type of compiler. Couse the inly place where i see name of compiler is name of directory, can you explain it please
![image](https://user-images.githubusercontent.com/20255584/99367227-bdef1800-28ca-11eb-8895-f9b01bcc7361.png)

**Comment by chunqishi** [comment]
I provided building details in [BUILDING.md](https://github.com/bibiparrot/vlc-qt/blob/master/BUILDING.md).
Also you can download the binary version: [releases](https://github.com/bibiparrot/vlc-qt/releases)

- Windows Build & Release with MinGW
- MinGW Win32/64 RelWithDebInfo Version
- VLC-Qt version: "1.2.0-9b2f561"
- libvlc version: "3.0.16 Vetinari"
- QT version: "15.5.2"

**Comment by levius0** [comment]
Thanks @chunqishi I succseeded!
