### ISSUE TITLE
core libvlc error: No plugins found! Check your VLC installation.

### ISSUE THREAD

**Issue by karamanh** [vlc-qt/vlc-qt#279]
Trying to run my vlc-qt application on an arm machine with Debian 8 on it. It compiled with no issue and is running but it crashes giving the following error message:

```
[0089c8b8] core libvlc error: No plugins found! Check your VLC installation.
VLC-Qt Error: libvlc failed to load! 
Segmentation fault
```
 
I downloaded vlc-qt from git, compiled and installed with some modifications on the target machine (i can give some details if needed, but i do not think this is relevant). What am i missing? I cannot find any plugins folder under ```/usr/lib/``` or ```/usr/local/lib``` or somewhere else. Installing libvlc5, libvlccore8, and libvlccore-dev did not help.

On my development machine, everything works, most probably because i have development and core libraries installed plus VLC itself is installed.
I saw on Google people experiencing this problem but their solutions are not working for me.

**Comment by ntadej** [comment]
You need to have basically full VLC installed. I think there's a non-GUI package also available if you do not want to have VLC Qt interface.

**Comment by karamanh** [comment]
Thank you for very quick response. To be completely sure, i do need a full VLC installation in order to run, for example, **simple-player** at https://github.com/vlc-qt/examples right (Which means i cannot deploy my application without a VLC installation)?

**Comment by ntadej** [comment]
The way VLC is distributed on Debian, no. Unless you bundle a custom build of VLC with your app only providing plugins that you actually need.
