### ISSUE TITLE
cannot build in win10 with msvc2019

### ISSUE THREAD

**Issue by be-water-myFriend** [vlc-qt/vlc-qt#283]
![image](https://user-images.githubusercontent.com/13702789/131301834-fdf37dc2-382c-4b97-b25a-2b9e5361aed0.png)

Build failed when run ninja cmd;

**Comment by wallrue** [comment]
The problem is caused by lacking of file "poll.h". This file was included in version 0.10.0 but I could not find it in the other versions. You should download file "poll.h" from https://github.com/vlc-qt/vlc-qt/tree/0.10.0/windows/msvc and #include it to the vlc_threads.h.

**Comment by be-water-myFriend** [comment]
@wallrue ok, thank you very much.
