### ISSUE TITLE
memory leak on play/stop stream in qml

### ISSUE THREAD

**Issue by pincopallopino** [vlc-qt/vlc-qt#34]
i'm on ubuntu 12.04 with vlc-qt 0.9.1 and vlc 2.1.3 

i'm using the example test of QML of the vlc-qt-master  archive but there is a memory leak when i stop and play a stream multiple times.
if i comment the line connectToMediaPlayer(_player) in the QmlVideoPlayer.cpp there aren't memory leaks. i also tried to comment the painting block to test if the problem is related with the painting but it seems that is only related to the setCallbacks, can someone help me?

**Comment by ntadej** [comment]
Can you please test with the latest version?

**Comment by long3009** [comment]
I tested with the lastest version but still leak. I think the reason is vlc library. Something isn't free after stop a stream

**Comment by ntadej** [comment]
Until someone can find a leak in VLC-Qt, I'm closing this issue.
