### ISSUE TITLE
Cannot use new syntax signal/slot for VlcMediaPlayer::mediaChanged

### ISSUE THREAD

**Issue by MBach** [vlc-qt/vlc-qt#45]
Hi,

I don't know if it's a real issue or not, but I cannot write:

    connect(_player, &VlcMediaPlayer::mediaChanged, this, [=](){
        //qDebug() << f;
        QMediaContent mc(_player->currentMedia()->currentLocation());
        emit currentMediaChanged(mc);
    });

I have to do this:

    connect(_player, SIGNAL(mediaChanged(libvlc_media_t*)), this, SLOT(convertMedia(libvlc_media_t*)));

and elsewhere in my class:

    void MediaPlayer::convertMedia(libvlc_media_t *)
    {
        QUrl url = QUrl::fromLocalFile(_player->currentMedia()->currentLocation());
        QMediaContent mc(url);
        emit currentMediaChanged(mc);
    }

I suppose it's a problem because `libvlc_media_t` is not fully defined at compile time (just a forward declaration)

**Comment by ntadej** [comment]
This will not/can not be fixed. Import VLC headers and it should work.
