### ISSUE TITLE
undefined reference to `_imp___ZN9VlcCommon4argsEv'

### ISSUE THREAD

**Issue by josereci** [vlc-qt/vlc-qt#57]
Hello. I have this problem. Please help Me!!

Thanks!

debug/DemoPlayer.o: In function `ZN10DemoPlayerC2EP7QWidget':
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/../../demo-player/src/DemoPlayer.cpp:37: undefined reference to `_imp___ZN9VlcCommon4argsEv'
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/../../demo-player/src/DemoPlayer.cpp:37: undefined reference to `_imp___ZN11VlcInstanceC1ERK11QStringListP7QObject'
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/../../demo-player/src/DemoPlayer.cpp:38: undefined reference to `_imp___ZN14VlcMediaPlayerC1EP11VlcInstance'
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/../../demo-player/src/DemoPlayer.cpp:39: undefined reference to `_imp___ZN14VlcMediaPlayer14setVideoWidgetEP16VlcVideoDelegate'
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/../../demo-player/src/DemoPlayer.cpp:41: undefined reference to `_imp___ZN14VlcWidgetVideo14setMediaPlayerEP14VlcMediaPlayer'
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/../../demo-player/src/DemoPlayer.cpp:42: undefined reference to `_imp___ZN21VlcWidgetVolumeSlider14setMediaPlayerEP14VlcMediaPlayer'
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/../../demo-player/src/DemoPlayer.cpp:43: undefined reference to `_imp___ZN21VlcWidgetVolumeSlider9setVolumeEi'
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/../../demo-player/src/DemoPlayer.cpp:44: undefined reference to `_imp___ZN13VlcWidgetSeek14setMediaPlayerEP14VlcMediaPlayer'
debug/DemoPlayer.o: In function `ZN10DemoPlayer9openLocalEv':
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/../../demo-player/src/DemoPlayer.cpp:74: undefined reference to `_imp___ZN8VlcMediaC1ERK7QStringbP11VlcInstance'
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/../../demo-player/src/DemoPlayer.cpp:76: undefined reference to `_imp___ZN14VlcMediaPlayer4openEP8VlcMedia'
debug/DemoPlayer.o: In function `ZN10DemoPlayer7openUrlEv':
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/../../demo-player/src/DemoPlayer.cpp:87: undefined reference to `_imp___ZN8VlcMediaC1ERK7QStringP11VlcInstance'
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/../../demo-player/src/DemoPlayer.cpp:89: undefined reference to `_imp___ZN14VlcMediaPlayer4openEP8VlcMedia'
debug/DemoPlayer.o: In function `ZN13Ui_DemoPlayer7setupUiEP11QMainWindow':
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/./ui_DemoPlayer.h:81: undefined reference to `_imp___ZN14VlcWidgetVideoC1EP7QWidget'
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/./ui_DemoPlayer.h:97: undefined reference to `_imp___ZN21VlcWidgetVolumeSliderC1EP7QWidget'
C:\Users\Pipe\Downloads\Lib3\examples\build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug\src/./ui_DemoPlayer.h:107: undefined reference to `_imp___ZN13VlcWidgetSeekC1EP7QWidget'
collect2.exe: error: ld returned 1 exit status
Makefile.Debug:80: recipe for target 'debug\demo-player.exe' failed
mingw32-make[2]: *** [debug\demo-player.exe] Error 1
mingw32-make[2]: Leaving directory 'C:/Users/Pipe/Downloads/Lib3/examples/build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug/src'
Makefile:34: recipe for target 'debug' failed
mingw32-make[1]: *** [debug] Error 2
mingw32-make[1]: Leaving directory 'C:/Users/Pipe/Downloads/Lib3/examples/build-demo-player-Desktop_Qt_5_3_MinGW_32bit-Debug/src'
Makefile:38: recipe for target 'sub-src-make_first' failed
mingw32-make: *** [sub-src-make_first] Error 2
12:16:41: The process "C:\Qt\Tools\mingw482_32\bin\mingw32-make.exe" exited with code 2.
Error while building/deploying project demo-player (kit: Desktop Qt 5.3 MinGW 32bit)
When executing step "Make"

**Comment by theiyerproject** [comment]
TARGET      = demo-player
TEMPLATE    = app

QT          += core gui widgets

SOURCES     += main.cpp\
               DemoPlayer.cpp

HEADERS     += DemoPlayer.h

FORMS       += DemoPlayer.ui

LIBS     += -LC:\Qt\libvlc-qt\lib -lvlc-qt -lvlc-qt-widgets
INCLUDEPATH += C:\Qt\libvlc-qt\include

This is my .pro file.
But I am still getting the above mentioned errors. Please help. Urgent help needed.
Thanks.

**Comment by ntadej** [comment]
I will update the examples for the next version and add some more documentation.

**Comment by ntadej** [comment]
Example has been updated. qmake still needs some install hooks, but examples run successfully.
