### ISSUE TITLE
ControlVideo - subtitleTracks signal problem

### ISSUE THREAD

**Issue by maximus321** [vlc-qt/vlc-qt#58]
I use theses 3 signals:

    connect(_controlVideo, SIGNAL(subtitleTracks(QList<QAction*>)), this, SLOT(subtitlesTrackChanged(QList<QAction*>)) );
    connect(_controlVideo, SIGNAL(videoTracks(QList<QAction*>)), this, SLOT(videoTracksChanged(QList<QAction*>)) );
    connect(_controlAudio, SIGNAL(audioTracks(QList<QAction*>)), this, SLOT(audioTracksChanged(QList<QAction*>)) );

They all work properly except for subtitleTracks in ControlVideo,  maybe it's an issue on newer VLC, i'm using 2.0.8 TwoFlower.  On windows, the subtitles action are mapped to my menu correctly but when I try to use the action, I get "libvlc Error: Track identifier not found".  On Mac OSX, using 2.1.4 Rincewind VLC,  the signal is not firing at all.

Thanks.

-------------------------------------
Starting C:\Dropbox\build-PowerVelo2-Desktop_Qt_5_2_1_MSVC2012_32bit-Release\release\MaximumTrainer.exe...
[042ca200] main interface error: no suitable interface module
libvlc-qt "0.9.0-dc9850a-git" initialised 
Using libvlc version: "2.0.8 Twoflower" 
libvlc Media: "D:/Film/Edge of Tomorrow/someMovie.mp4" Local: true 
QWidget::paintEngine: Should no longer be called
[0c2b0368] main vout display error: Failed to set on top
OK action audio  0  is QAction(0x7670c98) text "Disable" checked? false 
OK action audio  1  is QAction(0x7670ca8) text "Track 1 - [English]" checked? true 
audioTracksChanged*** 
OK action video  0  is QAction(0x761b560) text "Disable" checked? false 
OK action video  1  is QAction(0x7670ce8) text "Track 1" checked? true 
videoTracksChanged*** 
OK action subtitle  0  is QAction(0x7670cb8) text "Disable" checked? true 
OK action subtitle  1  is QAction(0x7670d28) text "Track 1" checked? false 
subtitlesTrackChanged*** 
Pause Player 
libvlc Error: Track identifier not found 
libvlc Error: Track identifier not found

**Comment by maximus321** [comment]
Hey ntadej, sorry for the delay.
Here is my player source code, containing the code in question :
https://www.dropbox.com/s/t95nnym688hrg2v/playerwidget.cpp?dl=0

Function with problems is "void PlayerWidget::subtitlesTrackChanged(QList<QAction*> lstAction)"
I get the error mentionned up here, for audio and video, all is fine.
Thanks

**Comment by ntadej** [comment]
Can you also provide video sample?

You can look at Tano Player code here:
https://github.com/ntadej/tano/tree/master/src/widgets/menu

**Comment by maximus321** [comment]
Seems like this was fixed using the latest vlc-qt, Thanks
