### ISSUE TITLE
build vlc-qt using vs2008 in win7 64

### ISSUE THREAD

**Issue by wearybird** [vlc-qt/vlc-qt#61]
i build vlc-qt(ver:0.9.0) using cmake-gui(ver:3.1.0) in win7 64.
i add entry :
     
![cmake-vlc-qt090](https://cloud.githubusercontent.com/assets/10044811/5277239/bba09dba-7b03-11e4-9c0b-140b1089ecc1.jpg)

i had build qt.2.1(msvc2008)
  when i configure ,select vs2008 ，there are some errors:
Found unsuitable Qt version "5.2.1" from H:/Qt/qtUXDskTop521Vs2008WebKitDR/bin/qmake.exe
CMake Error at H:/Qt/qtUXDskTop521Vs2008WebKitDR/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:16 (message):
  Failed to find "glu32" in "" with CMAKE_CXX_LIBRARY_ARCHITECTURE "".
Call Stack (most recent call first):
  H:/Qt/qtUXDskTop521Vs2008WebKitDR/lib/cmake/Qt5Gui/Qt5GuiConfigExtras.cmake:52 (_qt5gui_find_extra_libs)
  H:/Qt/qtUXDskTop521Vs2008WebKitDR/lib/cmake/Qt5Gui/Qt5GuiConfig.cmake:152 (include)
  H:/Qt/qtUXDskTop521Vs2008WebKitDR/lib/cmake/Qt5Widgets/Qt5WidgetsConfig.cmake:94 (find_package)
  CMakeLists.txt:103 (FIND_PACKAGE)

Configuring incomplete, errors occurred!
See also "E:/wangyun/VLC/vlc-qt-0.9.0/msvc2008build/CMakeFiles/CMakeOutput.log".

   how can i fix this errors?

**Comment by ntadej** [comment]
There were some improvements to build process. Please reopen this issue if you still encounter any problems.
