### ISSUE TITLE
How can I get current frame from the vlc-qt?

### ISSUE THREAD

**Issue by zqh619304288** [vlc-qt/vlc-qt#66]
Hello ntadej.
First of all thanks for this  library. 
I'm building a program in which I need to play video from rtsp,how can I get the frame data from the vlc-qt?

**Comment by ntadej** [comment]
What kind of data do you need? Do you want to draw it somewhere?

**Comment by jerrylouis** [comment]
Hi ntadej.

I must say "Brilliant API" you have built. Thanks
Just to add onto the same issue, I have used your examples to render the media onto a VlcWidgetVideo and works very well. Now I need to get access to these frames, case I'm trying to do some analytics with opencv. Is there a way I can get the frames, any pointers is much appreciated.

Thanks again,
Jerry

**Comment by ntadej** [comment]
You can try using VlcQmlVideoObject and VlcQmlVideoPlayer as a base. lockCallback, unlockCallback and displayCallback manage the communication with VLC.

**Comment by ntadej** [comment]
I'm reopening this as I'm working on something that may enable easier work. It's inspired by what QmlVlc but I'm trying to make it more modular and simpler to reuse or process frames.

**Comment by ntadej** [comment]
This is now merged. Subclass `VlcVideoStream` to get frame data.

**Comment by Shymaxtic** [comment]
HI ntadej, could you please give an example about using VlcVideoStream class to get frame data

**Comment by yicm** [comment]
@Shymaxtic 

```
// frameprocessor.hpp
class FrameProcessor : public VlcVideoStream
{
public:
    FrameProcessor(QObject *parent);
    void frameUpdated();
};

// frameprocessor.cpp
FrameProcessor::FrameProcessor(QObject *parent):
    VlcVideoStream(Vlc::YUVFormat, parent)
{

}

void FrameProcessor::frameUpdated() {
    qDebug() << "frame updated";
}
```

```
// formvideoplayer.cpp
    mFrameProcessor = new FrameProcessor(this);
    mInstance = new VlcInstance(VlcCommon::args(), this);
    mPlayer = new VlcMediaPlayer(mInstance);
    mPlayer->setVideoWidget(ui->video);
    ui->video->setMediaPlayer(mPlayer);

    mFrameProcessor->init(mPlayer);

```

**Comment by sajede-atefe** [comment]
I am using vlc2.2.1 and I subclassed VlcVideoStream and implemented frameUpdated() as the code above says. 
naw i have access to YUV frame in the (frame updated) function.
but it stops displaying the image in VlcVideoWidget(ui->video)  .

 but i need both displaying image in ui->video and accessing the YUV frame.
is there any solution to solve this problem?

**Comment by yicm** [comment]
@sajede-atefe hi, 

- are you sure you get the raw data? and checked it?
- in display, the same with you

**Comment by masgh021** [comment]
please make example for get frame and  convert  to opencv Mat .
