### ISSUE TITLE
Weird behavior with VlcMediaListPlayer

### ISSUE THREAD

**Issue by GWillmann** [vlc-qt/vlc-qt#68]
Hello and thank you for your hard work on this library.
I have a problem with VlcMediaListPlayer.

I took your demoplayer from the latest version of vlc-qt and tried to make a playlist.

```C++
VlcMediaList *mediaList = new VlcMediaList(_instance);
mediaList->addMedia(new VlcMedia("TEMP/jh.mp4", true, _instance));
mediaList->addMedia(new VlcMedia("Transitions/montagnes.jpg", true, _instance));
mediaList->addMedia(new VlcMedia("TEMP/azef_inv.mp4", true, _instance));

VlcMediaListPlayer *mediaListPlayer = new VlcMediaListPlayer(_player, _instance);
mediaListPlayer->setMediaList(mediaList);
mediaListPlayer->mediaPlayer()->play();
mediaListPlayer->next();
```

this setup works however the seekbar does not update any more and when a video is playing, the window seems to be unresponsive.
I am not sure I used correctly the VlcMediaListPlayer. It is weird that I can't do a simple 
```C++
mediaListPlayer->play();
```

Thank you for your reply!

**Comment by ntadej** [comment]
Sorry for late reply. I will try to look at the issue soon.

**Comment by ntadej** [comment]
I didn't find any specific issue. You can find a test in the tests folder which works for me.
