### ISSUE TITLE
VlcAudio setVolume method not settting volume in QT 4.8.6 in Ubuntu 14.04

### ISSUE THREAD

**Issue by manojpatidar** [vlc-qt/vlc-qt#70]
VlcAudio setVolume method not settting volume. Here is the code I am using.
        
        musicInstance = new VlcInstance(VlcCommon::args());
        musicPlayer = new VlcMediaPlayer(musicInstance);
        musicMedia = new VlcMedia(filename,true,musicInstance);
        musicAudio = musicPlayer->audio();
        musicAudio->setVolume(100);
        musicPlayer->open(musicMedia); 
    qDebug() << "MUSIC VOLUME:  "<< musicAudio->volume();

The same code is working fine and prints the right volume (in this case it is 100) in QT 5 in Windows7 but not working in QT4.8.6 in Ubuntu 14.04 (vlc-qt libraries not working in Qt 5 in Ubuntu 14.04).

So somehow I am able to set the volume In QT4.8.6 in Ubuntu 14.04 by setting the volume after 1 second delay using the below code and it is working fine.

        musicInstance = new VlcInstance(VlcCommon::args());
        musicPlayer = new VlcMediaPlayer(musicInstance);
        musicMedia = new VlcMedia(filename,true,musicInstance);
        musicAudio = musicPlayer->audio();
        // musicAudio->setVolume(100);
        musicPlayer->open(musicMedia);
      // Wait to set voume in Ubunntu
        QTimer::singleShot(1000, this, SLOT(setMusicVolume()));
     
  void MainWindow:: setMusicVolume(){
   musicAudio->setVolume(100);
    QTimer::singleShot(1000, this, SLOT(printMsg()));
}
void MainWindow::printMsg()
{
    qDebug() << "MUSIC VOLUME:  "<< musicAudio->volume();
}

But my issue is that I just want to avoid the 1second delay. Can anyone has idea so that I can fix my issue ?
 Thanks.

**Comment by ntadej** [comment]
You need to set audio after you start playback.

**Comment by manojpatidar** [comment]
Thank you ntadej for answering my question.

FYI, if you have a look on my above message and code in which I already somehow manage to set the volume of vlc media by setting voume after start playback as you suggested.

But my issue is that it sets the volume after delay of 1 sec or in less than 1 second and not set as soon as we set the voume in Qt 4.8.6, Ubuntu 14.04. So I just want to avoid the 1second delay.

**Comment by Toxsch** [comment]
Maybe you can try like this:

    QStringList args = VlcCommon::args();
    args <<  "--waveout-volume=1.0" << "--directx-volume=1.0";
    musicInstance = new VlcInstance(args);
    musicPlayer = new VlcMediaPlayer(musicInstance);
    musicMedia = new VlcMedia(filename,true,musicInstance);
    musicPlayer->open(musicMedia);

**Comment by manojpatidar** [comment]
Thanks Toxsch. I will as per you suggested and let you know.

**Comment by manojpatidar** [comment]
Toxsch, I have done as per you ( your above thread code), I got the following issue. 

vlc: unknown option or missing mandatory argument `--waveout-volume=1.0'
Try `vlc --help' for more information.

**Comment by Toxsch** [comment]
My mistake.
'waveout' and 'directx' are audio device on Windows.
You should run 'vlc -H' on Ubuntu to find the option.

**Comment by manojpatidar** [comment]
No problemToxsch. I will try from other sources and update my progress here.

**Comment by manojpatidar** [comment]
Toxsch, Can you please let me know the commands for the Ubuntu vlc version as you suggested for Windows ?
Btw, I am doing research to get the Ubuntu options or commands at my end. 

One more thing, did you test above your code or suggestion at your end in QT 4.8.6 in Ubuntu 14.04 ?

**Comment by Toxsch** [comment]
I'm using version 2.1.5.
I have been tested on Windows and OS X, it works fine. But had not been tested on Ubuntu

**Comment by kfieldi5** [comment]
Hey @ntadej , is there a way we can set volume before playback starts? I have my app reading volume from settings db and trying to set user preferred volume before I start playback.

**Comment by ntadej** [comment]
There is no way unfortunately. There will be some new events merged into master soon, maybe they can help. Otherwise, catch player signals and then set the audio.
