### ISSUE TITLE
Remove vlc-plugin-pulse from dependencies?

### ISSUE THREAD

**Issue by MBach** [vlc-qt/vlc-qt#76]
Shouldn't debian/control file updated with the following dependencies:
* modified: vlc >= 2.2.0
* removed: vlc-plugin-pulse (transitional package for vlc 2.2.0)

Or do you want to be retrocompatible with the old VLC 2.0?

**Comment by ntadej** [comment]
Is pulse plugin needed on 2.0 and 2.1? Otherwise I will remove all plugins in the next version.

Why would you remove support for old VLC versions? These Debian files are generic for all Debian based distributions. At least 2.1 will stay.

**Comment by MBach** [comment]
Ah! I was confused with the Changelog:
 * VLC 2.2 support

VLC 2.1.5 has a vlc-plugin-pulse which is not a transitional package but contains real stuff:
https://packages.debian.org/fr/wheezy-backports/vlc-plugin-pulse

**Comment by ntadej** [comment]
But is it necessary for core Libvlc usage?

**Comment by MBach** [comment]
I have no idea!

**Comment by ntadej** [comment]
I will test on 14.04. If it works without vlc-plugin-pulse, I will remove all plugins.
