### ISSUE TITLE
vlc-qt-0.10.0 demo-player issue with Win7 64-bit and Qt 5.4.1

### ISSUE THREAD

**Issue by allen-yang** [vlc-qt/vlc-qt#77]
system setup:
Win7 64-bit
VLC 2.1.5
downloaded and installed "qt-opensource-windows-x86-mingw491_opengl-5.4.1.exe"
downloaded and installed "libvlc-qt_0.10.0_win32_mingw.7z"

I compiled "demo-player". Compilation went well without problem. However, when I ran it in Qt, I got this message:

Starting C:\Qt\libvlc-qt\src\examples\build-demo-player-Desktop_Qt_5_4_1_MinGW_32bit-Debug\src\debug\demo-player.exe...
The program has unexpectedly finished.
C:\Qt\libvlc-qt\src\examples\build-demo-player-Desktop_Qt_5_4_1_MinGW_32bit-Debug\src\debug\demo-player.exe crashed

If I double click "demo-player.exe" to run it, I got an error message window saying "The application was unable to start correctly (0xc000007b)".

Any idea?

**Comment by ntadej** [comment]
Can you build and run debug version? It will help you solve the issue.

**Comment by allen-yang** [comment]
I tried building from source code but I got errors. The following are the steps:

1. Download and uncompress "VLC-Qt 0.10.0" source code from "https://github.com/ntadej/vlc-qt/releases". 

2. change cmake\FindLIBVLC.cmake to use my VLC path "c:/Program Files/VideoLAN/VLC/sdk/"

3. run command "cmake .. -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX=prefix" from CMake terminal.

4. run command "mingw32-make". I got a lot of errors like:
.............
CMakeFiles\vlc-qt.dir/objects.a(VideoMemoryStream.cpp.obj): In function `ZN20VlcVideoMemoryStream12setCallbacksEP14VlcMediaPlayer':
C:/Qt/vlc-qt-0.10.0-src/src/core/VideoMemoryStream.cpp:100: undefined reference to `libvlc_video_set_callbacks'
C:/Qt/vlc-qt-0.10.0-src/src/core/VideoMemoryStream.cpp:103: undefined reference to `libvlc_video_set_format_callbacks'
CMakeFiles\vlc-qt.dir/objects.a(VideoMemoryStream.cpp.obj): In function `ZN20Vlc VideoMemoryStream14unsetCallbacksEP14VlcMediaPlayer':
C:/Qt/vlc-qt-0.10.0-src/src/core/VideoMemoryStream.cpp:108: undefined reference to `libvlc_video_set_callbacks'
C:/Qt/vlc-qt-0.10.0-src/src/core/VideoMemoryStream.cpp:109: undefined reference to `libvlc_video_set_format_callbacks'
collect2.exe: error: ld returned 1 exit status
src\core\CMakeFiles\vlc-qt.dir\build.make:438: recipe for target 'src/core/libvlc-qt.dll' failed
mingw32-make[2]: *** [src/core/libvlc-qt.dll] Error 1
mingw32-make[2]: Leaving directory 'C:/Qt/vlc-qt-0.10.0-src/build'
CMakeFiles\Makefile2:130: recipe for target 'src/core/CMakeFiles/vlc-qt.dir/all' failed
mingw32-make[1]: *** [src/core/CMakeFiles/vlc-qt.dir/all] Error 2
mingw32-make[1]: Leaving directory 'C:/Qt/vlc-qt-0.10.0-src/build'
makefile:118: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

Another question is:
I installed "qt-opensource-windows-x86-mingw491_opengl-5.4.1.exe" which I think it builds 32-bit windows application. My Windows 7 machine is 64-bit. Should I install 32-bit VLC or 64-bit VLC?

Thank you very much.

**Comment by ntadej** [comment]
You should use 32-bit VLC for mingw builds.

**Comment by ntadej** [comment]
Examples have been updated and tested. They should run fine.
