### ISSUE TITLE
Runtime error on VlcInstance

### ISSUE THREAD

**Issue by Balmugen** [vlc-qt/vlc-qt#87]
Hello, 
I need to work on many media, that's why i love your work. But i have some problems, I can't use your program. I'm on Windows OS.
Problematics lines are :

instance=new VlcInstance(VlcCommon::args(),this);
player = new VlcMediaPlayer(instance);
videoWidget = new VlcWidgetVideo(player,this);
player->setVideoWidget(videoWidget); 

i have a Runtime error and this : 
QObject: Cannot create children for a parent that is in a different thread.
(Parent is MainWindow(0x28fdd8), parent's thread is QThread(0x12447d90), current thread is QThread(0x13de6500)

I don't create any thread. And the problem is from the VlcInstance. The Runtime come on the VlcWidgetVideo.

I'm sorry, i begin with QT and i don't have a really good experience on it. 

Thanks

**Comment by ntadej** [comment]
First try without passing parents with this.

Do you use designer to create UI? Then it might be better to create video widget there. (see promoted widgets).

**Comment by Balmugen** [comment]
Thanks for the first thread problem, "this" was the problem, i have used the "QWidget *parent" and he work for the VlcInstance.
For the other problem, the program work only in release and not in debugg mode, now i have my Video (in an other window but i will search to correct it). 
Thank you !

**Comment by ntadej** [comment]
Do you use windows? There is a known issue that debug mode has some problems there.

**Comment by agudpp** [comment]
I had the same issue. try to compile with CMAKE_BUILD_TYPE=Debug  and set DEBUG_SUFFIX=true.
I think using CMAKE_BUILD_TYPE=DEBUG didn't work, maybe I'm wrong.
That fixed the crash in debug. Hope it helps.

Nice lib by the way :+1:

**Comment by ntadej** [comment]
Can you first try running the example?

**Comment by ntadej** [comment]
Should work with latest master. Tested with examples.
