### ISSUE TITLE
Running QML application

### ISSUE THREAD

**Issue by joshmarshall95** [vlc-qt/vlc-qt#90]
Hello I am trying to simply get an RTSP feed to display on my QML application, within my C++ code I can easily get it to work but I can't seem to get my QML to recognise the plugins, in your example qml file you have the 'import VLCQt' how did you get that to import?

**Comment by ntadej** [comment]
An example will be written when time allows. Basically you need to do two things:

* In the main.cpp run `VlcQmlVideoPlayer::registerPlugin();`
* Import VLCQt with the version you use like `import VLCQt 0.11`. This will be improved in the future.

**Comment by joshmarshall95** [comment]
Okay thankyou for the reply. My code in my main is:
{
VlcQmlVideoPlayer::registerPlugin();
    QGuiApplication app(argc, argv);
    VlcQmlVideoPlayer::registerPlugin("C:/libvlc-qt_0.10.0_win32_msvc2013/bin/plugins");
    QtQuick2ApplicationViewer viewer;
    viewer.setMainQmlFile(QStringLiteral("qml/RTSP/main.qml"));
    viewer.showExpanded();
}

But within my QML I still fail to see the library from the import?

**Comment by joshmarshall95** [comment]
Could I please have the test-vlcqt-qml project? That application runs on my system but cannot get it to work with my project, we want to see what we are doing wrong within the setup.

**Comment by toanntww** [comment]
hi joshmarshall95,
I got the same issue to you on my environment: Win7 64, QT5.4, VS2013.
I've tried to install VLCQt module, sub-classing VlcQMLVideoPlayer but not successfully.
Then after I rebuild the vlc-qt-xml, It worked even if i have not re-built and re-linked my test project. 
I guest there are some step done while compiling vlc-qt-qml but not in pre-built package.
(sorry, i'm new to QML).

To build vlc-qt on Windows, you should also refer to: https://github.com/vlc-qt/vlc-qt/issues/65
other note: 
1. use VLC package with full sdk (sdk folder contains include, lib folder).
2. use latest vlc-qt code from git.
3. after succesfull buidling, VLCQT version is 0.11

**Comment by joshmarshall95** [comment]
Hi toanntww, It is not the issue with the library unfortunately. I have successfully linked the library to my project and can get subclasses to run. I just do not know how the libraries link to the qml.

**Comment by toanntww** [comment]
FYI, my test project:
.pro file:
```
TEMPLATE = app
QT += qml quick
INCLUDEPATH += D:\workspace\vlcqt\build\win64\include\vlc-qt
LIBS += -LD:\workspace\vlcqt\build\win64\lib -lvlc-qt -lvlc-qt-qml
SOURCES += main.cpp
RESOURCES += qml.qrc
QML_IMPORT_PATH =
include(deployment.pri)
HEADERS +=
```
qml file:
```
import QtQuick 2.0
import VLCQt 0.11
Rectangle {
    width: 640
    height: 480
    color: "black" 
    VlcVideoPlayer {
        id: vidwidget
        anchors.fill: parent
        url: "http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_640x360.m4v" 
    }
}
```

main.cpp file:
```
#include <QtCore/QTextCodec>
#include <QtGui/QGuiApplication>
#include <QtQuick/QQuickView>

#include <Common.h>
#include <Qmlvideoplayer.h>

int main(int argc, char *argv[])
{
    QGuiApplication app(argc, argv);
    QCoreApplication::setApplicationName("Test QML");
    QCoreApplication::setAttribute(Qt::AA_X11InitThreads);

    VlcQmlVideoPlayer::registerPlugin();
    VlcCommon::setPluginPath(app.applicationDirPath() + "./plugins");
    QQuickView view;;
    view.setSource(QUrl(QStringLiteral("qrc:/main.qml")));
    view.setResizeMode(QQuickView::SizeRootObjectToView);
    view.show();

    return app.exec();
}
```

**With prebuilt package**
above test project can be built and link correctly but got error: "module VLCQt is not installed".
i've tried replacing: 
``` 
VlcQmlVideoPlayer::registerPlugin();
```
by
```
qmlRegisterType<VlcQmlVideoPlayer>("VLCQt", 0, 11, "VlcVideoPlayer");
```
the QML gui was showed with a qml error message. I've not tested if the main function work in this case.

**workaround in my case**
rebuilt vlc-qt.

I'm not sure but this issue may relate to the process to build and link QML plugin. I could not found any solution to register the prebuilt QML package correctly.

**Comment by joshmarshall95** [comment]
Could you name the issue your compiler throws at you? My project looks almost identical to yours.. but whenever I try to import within my QML file there is the red error line underneath declaring that no module is found.

**Comment by joshmarshall95** [comment]
I've now gotten the import to work but it keeps crashing before it loads. Don't know if this is because the libraries do not link properly..

**Comment by toanntww** [comment]
sorry. After rebulding vlcqt, I cannot re-produce the issue to get the complete error message.
from my memory:
- original code: built succesfully, error occur while running: " module VLCQt is not installed"
- using qmlRegisterType(): built succesfully, qdebug fatal message while running: " class have fast property but no accessor". the QML GUI loaded but I have not tested if video function work in this case.

on my environment: i've linked the following libs:
1. QT_DIR/bin
2. vlcqt/bin:
 libvlc.dll
 libvlccore.dll
 libgcc_s_seh-1.dll
 vlc-qt.dll
 vlc-qt-qml.dll
 plugins/*
 platforms/*

Just sharing the information i got. hope it could help you in your case.

**Comment by ntadej** [comment]
The tests folder in the main repository is a good example for C++ code for integrating VLC-Qt in your application. I will try to make a QML example as soon as possible, but it's hard to test it on all platforms, especially as I don't know qmake much.

`VlcQmlVideoPlayer::registerPlugin();` should work fine. It exposes VLCQt module with the same version as current VLC-Qt.

There are also "nightly" builds available on http://download.tano.si so you don't have to build VLC-Qt completely by yourself if you need latest version for Windows and OS X.

**Comment by joshmarshall95** [comment]
Hi toantww and ntadej, I found a way to actually use the class but I had to use "qmlregistertype" before the import was recognised within my QML, when I got the import to work on QT it would not run the project, I had to generate the exe. and put it with all the dlls and only then could I see the project.

**Comment by ntadej** [comment]
QML example is now available. Project files are CMake only, but I think that the source is what matters.
