### ISSUE TITLE
Runtime error on plugin path

### ISSUE THREAD

**Issue by maximus321** [vlc-qt/vlc-qt#91]
Wondering if anyone found a fix to this error :
[00007f9109c4b6b8] core libvlc error: No plugins found! Check your VLC installation.
libvlc-qt Error: libvlc failed to load!

It happened since I tried to use 2.2.1 on osx 10.10. (was working fine before 2.2)
My .app is organized with both /lib and /plugins folder just close to the executable (like VLC.app)

I have tried to use "VlcCommon::setPluginPath("/plugins");" but to no success.
What is weird is that app is working inside QtCreator, but outside I get the error
Any tips on how to fix this is welcome, thanks!

**Comment by ntadej** [comment]
Since 2.2 VLC has different default search path vlc/plugins.

When setting the path you used absolute path. Remove / at the beginning.

**Comment by maximus321** [comment]
Thanks I changed the structure and created a subdirectory /vlc/plugins inside /lib
Now the VlcInstance doesn't crash but I get this:

libvlc-qt "Unknown" initialised
Using libvlc version: "2.2.1 Terry Pratchett (Weatherwax)"
[00007f89daa53ba8] core generic error: option vmem-chroma does not exist
[00007f89daa53ba8] core generic error: option vmem-width does not exist
[00007f89daa53ba8] core generic error: option vmem-height does not exist
...

I'm using the latest vlc-qt source from github and latest vlc source
Thanks for the help

**Comment by maximus321** [comment]
After further debugging, it seems even if you set your plugin path to "plugin" it still wants to look inside "vlc/plugin" and that is where it crashes for me :

[00007fa7dd3e6b88] core libvlc debug: loading plugins cache file /Users/tourlou3/build-PowerVelo2-Desktop_Qt_5_4_1_clang_64bit-Release/MaximumTrainer.app/Contents/MacOS/lib/vlc/plugins/plugins.dat
core libvlc warning: cannot read plugins/plugins.dat: No such file or directory

**Comment by ntadej** [comment]
I recommend that you patch libvlc using tools/osx_vlc_rpath_fix.sh. It will add rpath support on OS X.

**Comment by maximus321** [comment]
Here is the structure I have:
-Both /plugins and /lib folder are close to my @executable (like VLC.app)
-I have set my plugins path to "plugins" inside my app.

I compile my app, then copy /lib and /plugins from VLC.app to my myApp.app/Content/macOS
Then I tried to run the sh file on libvlc.5.dylib and libvlccore.8.dylib  but I still had the same error at runtime

sudo sh osx_vlc_rpath_fix.sh libvlc.5.dylib 
[osx_vlc_rpath_fix.sh] # Processing: 'libvlc.5.dylib'
@loader_path/lib/libvlc.5.dylib
[osx_vlc_rpath_fix.sh] install_name_tool -id @rpath/libvlc.5.dylib libvlc.5.dylib
loader_path/../lib/libvlccore.8.dylib
[osx_vlc_rpath_fix.sh] install_name_tool -change @loader_path/../lib/libvlccore.8.dylib @rpath/libvlccore.8.dylib libvlc.5.dylib
[osx_vlc_rpath_fix.sh] install_name_tool -add_rpath @loader_path/lib libvlc.5.dylib
[osx_vlc_rpath_fix.sh] # 'libvlc.5.dylib' is up-to-date


App crash log : 
[00007ff1fb0484d8] core libvlc warning: cannot read /Users/tourlou3/build-PowerVelo2-Desktop_Qt_5_4_1_clang_64bit-Release/MaximumTrainer.app/Contents/MacOS/lib/vlc/plugins/plugins.dat: No such file or directory
[00007ff1fb0484d8] core libvlc debug: recursively browsing `/Users/tourlou3/build-PowerVelo2-Desktop_Qt_5_4_1_clang_64bit-Release/MaximumTrainer.app/Contents/MacOS/lib/vlc/plugins'
[00007ff1fb0484d8] core libvlc debug: saving plugins cache /Users/tourlou3/build-PowerVelo2-Desktop_Qt_5_4_1_clang_64bit-Release/MaximumTrainer.app/Contents/MacOS/lib/vlc/plugins/plugins.dat
[00007ff1fb0484d8] core libvlc debug: loading plugins cache file plugins/plugins.dat
[00007ff1fb0484d8] core libvlc warning: cannot read plugins/plugins.dat: No such file or directory
[00007ff1fb0484d8] core libvlc debug: recursively browsing `plugins'
[00007ff1fb0484d8] core libvlc debug: saving plugins cache plugins/plugins.dat
[00007ff1fb0484d8] core libvlc debug: plug-ins loaded: 1 modules
[00007ff1fb0484d8] core libvlc debug: translation test: code is "C"
[00007ff1fb0484d8] core libvlc error: No plugins found! Check your VLC installation.
libvlc-qt Error: libvlc failed to load!
Abort trap: 6

Would really like to fix this, been trying for 2 days to make it work -_-   I'm no mac expert, a workaround would work for me..  Thanks

**Comment by ntadej** [comment]
Try this: `VlcCommon::setPluginPath(app.applicationDirPath() + "/plugins");`

**Comment by maximus321** [comment]
Genius!

**Comment by maximus321** [comment]
What would be good to have is a small documentation on how to integrate and deploy vlc-qt on OSX and Windows.

Example .pro file with links needed in order to run vlc-qt with latest libvlc.
Thanks

**Comment by ntadej** [comment]
VLC-Qt should be compiled using CMake. This is the only supported way and it works on all platforms.

As for examples. There is an examples repository in making, but I don't know qmake much so contributions are welcome.

**Comment by ntadej** [comment]
There are also "nightly" builds available on http://download.tano.si so you don't have to build VLC-Qt completely by yourself if you need latest version for Windows and OS X.

**Comment by maximus321** [comment]
Thanks Tadej this is exactly what I needed, the nightly build are perfect and will save me a lot of headaches trying to compile myself.
Wish I knew that earlier! love vlc-qt and what you are doing!
Max

**Comment by ntadej** [comment]
I just recently set up these nightlies. I will try to complete two separate examples for widgets and QML, but no promises.

**Comment by maximus321** [comment]
I could help for the widgets example, my player is build used the QWidget style

**Comment by maximus321** [comment]
Well with the nightly it was easy!

win32 {
    #using VLC-Qt nightly builds - http://download.tano.si/
    LIBS        += -lvlc-qt -lvlc-qt-widgets
    LIBS += -LC:\Dropbox\VLC-Qt_0.11.0_build11_893f101_win32_msvc2013\lib
    INCLUDEPATH += C:\Dropbox\VLC-Qt_0.11.0_build11_893f101_win32_msvc2013\include
}

macx {
    LIBS        += -lvlc-qt -lvlc-qt-widgets
    LIBS += -L/Users/tourlou3/Dropbox/VLC-Qt_0.11.0_build32_893f101/lib
    INCLUDEPATH +=  /Users/tourlou3/Dropbox/VLC-Qt_0.11.0_build32_893f101/include
}

On Windows, just had to copy all the .dll to /release
Only thing is that on OSX it's linking my app to :
	@rpath/libvlc-qt.0.11.dylib (compatibility version 0.11.0, current version 0.11.0)
	@rpath/libvlc-qt-widgets.0.11.dylib (compatibility version 0.11.0, current version 0.11.0)

Not sure what @rpath means, I tried to copy the lib all around inside my .app without success. Any way to fix that without using install_name_tool manually?
Thanks again, once i'm set hopefully I can contribute instead of asking help ;)

**Comment by ntadej** [comment]
Some reading about the rpath: http://www.cmake.org/Wiki/CMake_RPATH_handling
Basically it's a path for the app to look at for libraries. Google says you can set it in qmake via `QMAKE_RPATHDIR += lib/` for example for lib subdirectory relative to executable.

**Comment by maximus321** [comment]
Thanks, finally the solution was :
    QMAKE_RPATHDIR += @executable_path/../Frameworks
    QMAKE_RPATHDIR += @executable_path/lib

RPATH is powerful once you learn how it works.. 
/issue closed!
