### ISSUE TITLE
bitshifted file at runtime?

### ISSUE THREAD

**Issue by dkomer** [vlc-qt/vlc-qt#92]
Not sure if this is the best place to ask this question... if there's a forum or something, I'm happy to keep these kinds of questions there... but in the meantime-

What would be the overall way to supply a custom file (stream of bytes) at runtime?

i.e. if I wanted to decrypt an mp4 that was encrypted with a stream cipher and supply that data, and still have it work smoothly with seeking, thumbnail screens, etc.

Ideally would be if the library accepted some sort of class that had methods which are expected to provide the correct bytes from a given offset, as opposed to a path to file://, http:// - or something like that...

Even just pointing in the right direction would be helpful at this point.

Thanks for the leads!

**Comment by dkomer** [comment]
This can be done using video filters. I tried something like this in simpleplayer and it worked perfectly to add the sepia filter to the chain:

QStringList VlcArgs = VlcCommon::args();
VlcArgs << "--video-filter=sepia";
VlcArgs << "--sepia-intensity=200";

_instance = new VlcInstance(VlcArgs, this);

**Comment by ntadej** [comment]
To address the question - forum is coming soon :)

**Comment by dkomer** [comment]
Cool :) BTW- for reference, better than video-filter for this exact thing is stream-filter, though the available plugins (smooth, dash, record) seem to be something that's detected by filetype or something, i.e. setting --stream-filter=record or --stream-filter=smooth doesn't do anything
