### ISSUE TITLE
Add debug version to nightly builds

### ISSUE THREAD

**Issue by dkomer** [vlc-qt/vlc-qt#93]
Feature request, otherwise qt-creator throws this error when developing against vlc-qt in debug mode (even for simpleplayer example):

QWidget: Must construct a QApplication before a QWidget

**Comment by ntadej** [comment]
There is a debug folder in the archive.

**Comment by dkomer** [comment]
Thanks :)

**Comment by aliks-os** [comment]
Sorry, but I have the same problem, please point me where I can find the debug version

**Comment by ntadej** [comment]
Use the latest master build on AppVeyor.

**Comment by aliks-os** [comment]
Sorry, I never used AppVeyor before, can you give me a links from where I can downloaw win64 version (release and debug) for msvs2015
