### ISSUE TITLE
Display seekbar widget on top of video widget

### ISSUE THREAD

**Issue by dakom** [vlc-qt/vlc-qt#94]
Currently, once video starts playing, the seekbar will disappear unless they are each in their own part of the window. Is there any way to display the seekbar on top of the video widget?

**Comment by ntadej** [comment]
VLC replaces the whole widget when drawing the video in it. It is impossible to have children inside. It is possible in QML though.

**Comment by dkomer** [comment]
Interesting... how do they do it in their VLC Media Player, a separate window of some sort?

**Comment by ntadej** [comment]
Do you mean fullscreen controls widget? It's just floating over the video. I do the same in my Tano player.

**Comment by dkomer** [comment]
Ah... yeah... I'd like to do something like that but feel like an overlay. Best example for what I have in mind is from non-qt player @ comedy central (i.e. http://thecolbertreport.cc.com/videos/w5h8eb/kendrick-lamar)

I'm brand-new to Qt... from what I'm understanding- you're saying there's a way of having two different widgets (not windows) overlaying without having one actually be a child of the other?
