### ISSUE TITLE
Preview Frame, setVolume freeze

### ISSUE THREAD

**Issue by Alegr37** [vlc-qt/vlc-qt#96]
Hello, first of all thanks for your great work! It's amazing!

I beginner in vlc-lib and dont know few things?
Can you help me?
I dont know, how can I get preview frame with VLC, like it's working on YouTube
(if it possible, of course) :(
https://goo.gl/photos/EiWfsNUoCotkBANv8  

And second question, is about sound volume.
In QML volume changed with some freeze:
https://goo.gl/photos/EUEMKmiCCb8zNvrY6

It's a normal, or some bug?
Sorry for my bad English :o

**Comment by ntadej** [comment]
1) I think currently it's not possible to get preview frame for current media. You might be able to play 2 times and get frame from another player.

2) How long does it take to switch volume. Milliseconds or seconds?

**Comment by Alegr37** [comment]
1) is too resource-intensive, it is necessary to come up with something else
2) About half a second, it becomes clearly visible when you change the volume in different directions

offtop: Why you not use "public slots" for "WRITE" functions? I thought that their use is preferable

**Comment by Alegr37** [comment]
signal volumeChanged emits before changes applyed
