### ISSUE TITLE
Media player failed to change output widget

### ISSUE THREAD

**Issue by whatastupidname** [vlc-qt/vlc-qt#97]
I need to change the output widget, but I can't make it without creating a new player. This issue should be caused by some bugs of vlc. I used vlc the other day, got the same error. I'm using vlc-qt 0.10, qt5.4.2, windows10. 
void MainWindow::playVideo(QString fileName, VlcWidgetVideo *wid){
    if(wid!=_player->videoWidget()){
        delete _player;
        _player = new VlcMediaPlayer(_instance);
        connect(_player,SIGNAL(end()),this,SLOT(emitEnd()));
    }
    auto media = new VlcMedia(fileName,true,_instance);
    _player->setVideoWidget(wid);
    wid->setMediaPlayer(_player);
    _player->open(media);
}

Btw, I always the error message "qwidget: must construct a qapplication before a qwidget" when building the demo-player in debug mode. If I build it in release mode, everythin works perfectly. Do you have any idea?

**Comment by ntadej** [comment]
Should work with latest master. Tested with examples.
